-- MySQL Script generated by MySQL Workbench
-- Tue Jun 27 13:37:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RelationsAndConclusions
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `RelationsAndConclusions` ;

-- -----------------------------------------------------
-- Schema RelationsAndConclusions
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RelationsAndConclusions` ;
-- -----------------------------------------------------
-- Schema Cultural_violence
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Cultural_violence` ;

-- -----------------------------------------------------
-- Schema Cultural_violence
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cultural_violence` ;
-- -----------------------------------------------------
-- Schema GENDER_VIOLENCE
-- -----------------------------------------------------
-- 	
DROP SCHEMA IF EXISTS `GENDER_VIOLENCE` ;

-- -----------------------------------------------------
-- Schema GENDER_VIOLENCE
--
-- 	
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GENDER_VIOLENCE` ;
-- -----------------------------------------------------
-- Schema Structural_Violence
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Structural_Violence` ;

-- -----------------------------------------------------
-- Schema Structural_Violence
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Structural_Violence` ;
-- -----------------------------------------------------
-- Schema Phisical_violence
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Phisical_violence` ;

-- -----------------------------------------------------
-- Schema Phisical_violence
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Phisical_violence` ;
USE `RelationsAndConclusions` ;

-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`EducationalCenters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`EducationalCenters` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`EducationalCenters` (
  `id` INT NULL DEFAULT NULL,
  `educational_center_id` INT NULL DEFAULT NULL,
  `educational_center_name` VARCHAR(255) NULL DEFAULT NULL,
  `teaching_level` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  UNIQUE INDEX (`educational_center_id` ASC) VISIBLE,
  INDEX `fk_EducationalCenters_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_EducationalCenters_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`IcfesTestResults`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`IcfesTestResults` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`IcfesTestResults` (
  `id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `final_violence_index` INT NULL DEFAULT NULL,
  `math_performance` INT NULL DEFAULT NULL,
  `natural_sciences_performance` INT NULL DEFAULT NULL,
  `social_and_citizenship_performance` INT NULL DEFAULT NULL,
  `languages_performance` INT NULL DEFAULT NULL,
  `foreign_language_performance` INT NULL DEFAULT NULL,
  `global_performance` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_IcfesTestResults_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_IcfesTestResults_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`Municipalitie_Information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`Municipalitie_Information` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`Municipalitie_Information` (
  `Municipalities_id` INT NOT NULL,
  `Municipalitie_name` VARCHAR(45) NOT NULL,
  `Department_name` VARCHAR(45) NOT NULL,
  `ID_Deparment` INT NOT NULL,
  PRIMARY KEY (`Municipalities_id`),
  UNIQUE INDEX `Municipalities_id_UNIQUE` (`Municipalities_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`PopulationInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`PopulationInformation` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`PopulationInformation` (
  `id` INT NULL DEFAULT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `population` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `YEARS_idYEARS`, `Municipalitie_Information_Municipalities_id`),
  UNIQUE INDEX (`population` ASC) VISIBLE,
  INDEX `fk_PopulationInformation_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  INDEX `fk_PopulationInformation_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_PopulationInformation_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PopulationInformation_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`Probes_references`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`Probes_references` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`Probes_references` (
  `idProbes_references` INT NOT NULL,
  `Year` YEAR(4) NULL,
  `Period` INT NULL,
  `People_Who_takes_probes` INT NULL,
  PRIMARY KEY (`idProbes_references`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`STU_reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`STU_reference` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`STU_reference` (
  `Id_stu` INT NOT NULL,
  `EducationalCenters_id` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `Probes_references_idProbes_references` INT NOT NULL,
  PRIMARY KEY (`Id_stu`, `EducationalCenters_id`, `Municipalitie_Information_Municipalities_id`, `Probes_references_idProbes_references`),
  INDEX `fk_STU_reference_EducationalCenters1_idx` (`EducationalCenters_id` ASC) VISIBLE,
  INDEX `fk_STU_reference_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_STU_reference_Probes_references1_idx` (`Probes_references_idProbes_references` ASC) VISIBLE,
  UNIQUE INDEX `Id_stu_UNIQUE` (`Id_stu` ASC) VISIBLE,
  CONSTRAINT `fk_STU_reference_EducationalCenters1`
    FOREIGN KEY (`EducationalCenters_id`)
    REFERENCES `RelationsAndConclusions`.`EducationalCenters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STU_reference_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STU_reference_Probes_references1`
    FOREIGN KEY (`Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`YEARS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`YEARS` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`YEARS` (
  `idYEARS` INT NOT NULL,
  `YEARScol` YEAR(4) NOT NULL,
  PRIMARY KEY (`idYEARS`),
  UNIQUE INDEX `YEARScol_UNIQUE` (`YEARScol` ASC) VISIBLE)
ENGINE = InnoDB;

USE `Cultural_violence` ;

-- -----------------------------------------------------
-- Table `Cultural_violence`.`Books_for_Family_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Books_for_Family_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Books_for_Family_influence` (
  `id` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `books_for_family` INT NULL,
  `books_for_family_indicator` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `YEARS_idYEARS`, `Municipalitie_Information_Municipalities_id`),
  UNIQUE INDEX `id_Stu_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Books_for_Family_influence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_Books_for_Family_influence_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  CONSTRAINT `fk_Books_for_Family_influence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Books_for_Family_influence_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Books_for_family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Books_for_family` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Books_for_family` (
  `idBooks_for_family` INT NOT NULL,
  `Number_books_abv` VARCHAR(45) NULL,
  PRIMARY KEY (`idBooks_for_family`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cultural_violence`.`CulturalInfluence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`CulturalInfluence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`CulturalInfluence` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Year` YEAR(4) NULL,
  `municipality_id` INT NOT NULL,
  `ethnic_Influencer_indicator` DECIMAL NOT NULL,
  `books_for_family_indicator` DECIMAL NOT NULL,
  `Stu_internet_influence_indicator` DECIMAL NOT NULL,
  `Stu_read_for_pleasure_indicator` DECIMAL NOT NULL,
  `Year` DECIMAL NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  PRIMARY KEY (`Id`, `Municipalitie_Information_Municipalities_id`, `YEARS_idYEARS`),
  INDEX `Iindx_subin_cultural_influence` (`Year` ASC) VISIBLE,
  INDEX `fk_CulturalInfluence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_CulturalInfluence_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  CONSTRAINT `fk_CulturalInfluence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CulturalInfluence_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`CulturalViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`CulturalViolenceIndex` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`CulturalViolenceIndex` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NOT NULL,
  `year` YEAR(4) NULL,
  `subin_Ancestry_homicide` FLOAT NULL DEFAULT NULL,
  `subin_Ancestry_suicide` FLOAT NULL DEFAULT NULL,
  `subin_vulnerable_groups_homicide` FLOAT NULL DEFAULT NULL,
  `subin_vulnerability_suicide` FLOAT NULL DEFAULT NULL,
  `contex_violence_index` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `Iindx_cultural_violence_index` (`contex_violence_index` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Educational-Level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Educational-Level` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Educational-Level` (
  `idEducational-Level` INT NOT NULL,
  `Educational level` VARCHAR(45) NULL,
  PRIMARY KEY (`idEducational-Level`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Father_Educational_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Father_Educational_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Father_Educational_influence` (
  `id` INT NOT NULL,
  `Id_mun` INT NULL DEFAULT NULL,
  `Year` YEAR(4) NULL,
  `Father_Educational_influence` DOUBLE NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `YEARS_idYEARS`),
  INDEX `idx_Stu_read_for_pleasure_indicator` (`Id_mun` ASC) VISIBLE,
  UNIQUE INDEX `id_Stu_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Father_Educational_influence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_Father_Educational_influence_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  CONSTRAINT `fk_Father_Educational_influence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Father_Educational_influence_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Hours_of_ dedication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Hours_of_ dedication` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Hours_of_ dedication` (
  `IDHours Internet-Reading` INT NOT NULL,
  `Number of hours` VARCHAR(45) NULL,
  PRIMARY KEY (`IDHours Internet-Reading`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Hours_of_Reading_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Hours_of_Reading_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Hours_of_Reading_influence` (
  `id` INT NOT NULL,
  `Year` YEAR(4) NULL,
  `Hours_of_reading_indicator` DOUBLE NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `YEARS_idYEARS`),
  UNIQUE INDEX `id_Stu_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Hours_of_Reading_influence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_Hours_of_Reading_influence_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  CONSTRAINT `fk_Hours_of_Reading_influence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hours_of_Reading_influence_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`InternetAccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`InternetAccess` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`InternetAccess` (
  `id` INT NULL DEFAULT NULL,
  `municipality_id` INT NULL DEFAULT NULL,
  `Internet_access` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Cultural_violence`.`InternetAccess_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`InternetAccess_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`InternetAccess_influence` (
  `id` INT NULL AUTO_INCREMENT,
  `count_cases_true` INT NULL DEFAULT NULL,
  `subin_Internet_access` FLOAT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_InternetAccess_influence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_InternetAccess_influence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Interpersonal_Conflicts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Interpersonal_Conflicts` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Interpersonal_Conflicts` (
  `id` INT NOT NULL,
  `occurrences` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `subin_Interpersonal_conflicts` FLOAT GENERATED ALWAYS AS () VIRTUAL,
  `PopulationInformation_id` INT NOT NULL,
  `Years_idYears` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `PopulationInformation_id`, `Years_idYears`),
  INDEX `Iindxsubin_vulnerable_groups_homicide` (`subin_Interpersonal_conflicts` ASC) VISIBLE,
  INDEX `fk_Interpersonal_Conflicts_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_Interpersonal_Conflicts_PopulationInformation1_idx` (`PopulationInformation_id` ASC) VISIBLE,
  CONSTRAINT `fk_Interpersonal_Conflicts_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interpersonal_Conflicts_PopulationInformation1`
    FOREIGN KEY (`PopulationInformation_id`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Interpersonal_Homicide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Interpersonal_Homicide` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Interpersonal_Homicide` (
  `id` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `PopulationInformation_id` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  `occurrences` INT NULL DEFAULT NULL,
  `subin_vulnerable_groups_homicide` FLOAT GENERATED ALWAYS AS (),
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `PopulationInformation_id`, `YEARS_idYEARS`),
  INDEX `Iindxsubin_vulnerable_groups_homicide` (`subin_vulnerable_groups_homicide` ASC) VISIBLE,
  INDEX `fk_Interpersonal_Homicide_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_Interpersonal_Homicide_PopulationInformation1_idx` (`PopulationInformation_id` ASC) VISIBLE,
  INDEX `fk_Interpersonal_Homicide_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  CONSTRAINT `fk_Interpersonal_Homicide_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interpersonal_Homicide_PopulationInformation1`
    FOREIGN KEY (`PopulationInformation_id`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interpersonal_Homicide_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Mother_Educational_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Mother_Educational_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Mother_Educational_influence` (
  `id` INT NOT NULL,
  `Mother_Educational_influence` DOUBLE NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  UNIQUE INDEX `id_Stu_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Mother_Educational_influence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_Mother_Educational_influence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`RACIAL_ANC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`RACIAL_ANC` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`RACIAL_ANC` (
  `idRACIAL_ANC` INT NOT NULL,
  PRIMARY KEY (`idRACIAL_ANC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cultural_violence`.`RacialAncestryHomicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`RacialAncestryHomicideViolence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`RacialAncestryHomicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `PopulationInformation_id` INT NOT NULL,
  `RACIAL_ANC_idRACIAL_ANC` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  `occurrences` INT NULL DEFAULT NULL,
  `subin_homicide` FLOAT GENERATED ALWAYS AS (),
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `PopulationInformation_id`, `RACIAL_ANC_idRACIAL_ANC`, `YEARS_idYEARS`),
  INDEX `Iindx_subin_homicide` (`subin_homicide` ASC) VISIBLE,
  INDEX `fk_RacialAncestryHomicideViolence_Municipalitie_Information_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_RacialAncestryHomicideViolence_PopulationInformation1_idx` (`PopulationInformation_id` ASC) VISIBLE,
  INDEX `fk_RacialAncestryHomicideViolence_RACIAL_ANC1_idx` (`RACIAL_ANC_idRACIAL_ANC` ASC) VISIBLE,
  INDEX `fk_RacialAncestryHomicideViolence_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  CONSTRAINT `fk_RacialAncestryHomicideViolence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RacialAncestryHomicideViolence_PopulationInformation1`
    FOREIGN KEY (`PopulationInformation_id`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RacialAncestryHomicideViolence_RACIAL_ANC1`
    FOREIGN KEY (`RACIAL_ANC_idRACIAL_ANC`)
    REFERENCES `Cultural_violence`.`RACIAL_ANC` (`idRACIAL_ANC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RacialAncestryHomicideViolence_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`RacialAncestrySuicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`RacialAncestrySuicideViolence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`RacialAncestrySuicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `PopulationInformation_id` INT NOT NULL,
  `occurrences` INT NULL DEFAULT NULL,
  `subin_suicide` FLOAT GENERATED ALWAYS AS () VIRTUAL,
  `RACIAL_ANC_idRACIAL_ANC` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `PopulationInformation_id`, `RACIAL_ANC_idRACIAL_ANC`, `YEARS_idYEARS`),
  INDEX `Iindx_subin_suicide` (`subin_suicide` ASC) VISIBLE,
  INDEX `fk_RacialAncestrySuicideViolence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_RacialAncestrySuicideViolence_PopulationInformation1_idx` (`PopulationInformation_id` ASC) VISIBLE,
  INDEX `fk_RacialAncestrySuicideViolence_RACIAL_ANC1_idx` (`RACIAL_ANC_idRACIAL_ANC` ASC) VISIBLE,
  INDEX `fk_RacialAncestrySuicideViolence_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  CONSTRAINT `fk_RacialAncestrySuicideViolence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RacialAncestrySuicideViolence_PopulationInformation1`
    FOREIGN KEY (`PopulationInformation_id`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RacialAncestrySuicideViolence_RACIAL_ANC1`
    FOREIGN KEY (`RACIAL_ANC_idRACIAL_ANC`)
    REFERENCES `Cultural_violence`.`RACIAL_ANC` (`idRACIAL_ANC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RacialAncestrySuicideViolence_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`SociopoliticHomicide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`SociopoliticHomicide` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`SociopoliticHomicide` (
  `id` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `PopulationInformation_id` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `PopulationInformation_id`, `YEARS_idYEARS`),
  INDEX `fk_SociopoliticHomicide_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_SociopoliticHomicide_PopulationInformation1_idx` (`PopulationInformation_id` ASC) VISIBLE,
  INDEX `fk_SociopoliticHomicide_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  CONSTRAINT `fk_SociopoliticHomicide_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SociopoliticHomicide_PopulationInformation1`
    FOREIGN KEY (`PopulationInformation_id`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SociopoliticHomicide_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Stu_Father_educational_Level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_Father_educational_Level` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_Father_educational_Level` (
  `Id` INT NOT NULL,
  `EducationalCenters_id` INT NOT NULL,
  `Educational-Level_idEducational-Level` INT NOT NULL,
  `Probes_references_idProbes_references` INT NOT NULL,
  `STU_reference_Id_stu` INT NOT NULL,
  PRIMARY KEY (`EducationalCenters_id`, `Id`, `Educational-Level_idEducational-Level`, `Probes_references_idProbes_references`, `STU_reference_Id_stu`),
  INDEX `fk_Stu_Father_educational_Level_EducationalCenters1_idx` (`EducationalCenters_id` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Stu_Father_educational_Level_Educational-Level1_idx` (`Educational-Level_idEducational-Level` ASC) VISIBLE,
  INDEX `fk_Stu_Father_educational_Level_Probes_references1_idx` (`Probes_references_idProbes_references` ASC) VISIBLE,
  INDEX `fk_Stu_Father_educational_Level_STU_reference1_idx` (`STU_reference_Id_stu` ASC) VISIBLE,
  CONSTRAINT `fk_Stu_Father_educational_Level_EducationalCenters1`
    FOREIGN KEY (`EducationalCenters_id`)
    REFERENCES `RelationsAndConclusions`.`EducationalCenters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_Father_educational_Level_Educational-Level1`
    FOREIGN KEY (`Educational-Level_idEducational-Level`)
    REFERENCES `Cultural_violence`.`Educational-Level` (`idEducational-Level`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_Father_educational_Level_Probes_references1`
    FOREIGN KEY (`Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_Father_educational_Level_STU_reference1`
    FOREIGN KEY (`STU_reference_Id_stu`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`Id_stu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Stu_books_for_Family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_books_for_Family` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_books_for_Family` (
  `ID` INT NOT NULL,
  `Id_stu` INT NOT NULL,
  `EducationalCenters_id` VARCHAR(45) NOT NULL,
  `Books_for_family_idBooks_for_family` INT NOT NULL,
  `Probes_references_idProbes_references` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  PRIMARY KEY (`Id_stu`, `EducationalCenters_id`, `ID`, `Books_for_family_idBooks_for_family`, `Probes_references_idProbes_references`, `YEARS_idYEARS`),
  INDEX `fk_Stu_books_for_Family_Saber_reference1_idx` (`Id_stu` ASC) VISIBLE,
  INDEX `fk_Stu_books_for_Family_EducationalCenters1_idx` (`EducationalCenters_id` ASC) VISIBLE,
  INDEX `fk_Stu_books_for_Family_Books_for_family1_idx` (`Books_for_family_idBooks_for_family` ASC) VISIBLE,
  INDEX `fk_Stu_books_for_Family_Probes_references1_idx` (`Probes_references_idProbes_references` ASC) VISIBLE,
  INDEX `fk_Stu_books_for_Family_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  CONSTRAINT `fk_Stu_books_for_Family_Saber_reference1`
    FOREIGN KEY (`Id_stu`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`Id_stu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_books_for_Family_EducationalCenters1`
    FOREIGN KEY (`EducationalCenters_id`)
    REFERENCES `RelationsAndConclusions`.`EducationalCenters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_books_for_Family_Books_for_family1`
    FOREIGN KEY (`Books_for_family_idBooks_for_family`)
    REFERENCES `Cultural_violence`.`Books_for_family` (`idBooks_for_family`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_books_for_Family_Probes_references1`
    FOREIGN KEY (`Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_books_for_Family_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Stu_hours_Internet_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_hours_Internet_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_hours_Internet_influence` (
  `ID` INT NOT NULL,
  `STU_reference_Id_stu` INT NOT NULL,
  `Saber_reference_Id_stu` INT NOT NULL,
  `EducationalCenters_id` INT NOT NULL,
  `table1_IDHours Internet-Reading` INT NOT NULL,
  `Probes_references_idProbes_references` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  PRIMARY KEY (`ID`, `STU_reference_Id_stu`, `Saber_reference_Id_stu`, `EducationalCenters_id`, `table1_IDHours Internet-Reading`, `Probes_references_idProbes_references`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`, `YEARS_idYEARS`),
  INDEX `fk_Stu_hours_Internet_influence_table11_idx` (`table1_IDHours Internet-Reading` ASC) VISIBLE,
  INDEX `fk_Stu_hours_Internet_influence_EducationalCenters1_idx` (`EducationalCenters_id` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Stu_hours_Internet_influence_Saber_reference2_idx` (`Saber_reference_Id_stu` ASC) VISIBLE,
  INDEX `fk_Stu_hours_Internet_influence_Probes_references1_idx` (`Probes_references_idProbes_references` ASC) VISIBLE,
  INDEX `fk_Stu_hours_Internet_influence_STU_reference1_idx` (`STU_reference_Id_stu` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  INDEX `fk_Stu_hours_Internet_influence_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  CONSTRAINT `fk_Stu_hours_Internet_influence_Saber_reference1`
    FOREIGN KEY ()
    REFERENCES `RelationsAndConclusions`.`STU_reference` ()
    ON DELETE NO ACTION
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Stu_hours_Internet_influence_table11`
    FOREIGN KEY (`table1_IDHours Internet-Reading`)
    REFERENCES `Cultural_violence`.`Hours_of_ dedication` (`IDHours Internet-Reading`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_hours_Internet_influence_EducationalCenters1`
    FOREIGN KEY (`EducationalCenters_id`)
    REFERENCES `RelationsAndConclusions`.`EducationalCenters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_hours_Internet_influence_Saber_reference2`
    FOREIGN KEY (`Saber_reference_Id_stu`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`Id_stu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_hours_Internet_influence_Probes_references1`
    FOREIGN KEY (`Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_hours_Internet_influence_STU_reference1`
    FOREIGN KEY (`STU_reference_Id_stu` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`Id_stu` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_hours_Internet_influence_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Stu_hours_reading_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_hours_reading_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_hours_reading_influence` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Saber_reference_Id_stu` INT NOT NULL,
  `Hours of dedication_IDHours Internet-Reading` INT NOT NULL,
  `EducationalCenters_id` INT NOT NULL,
  `Probes_references_idProbes_references` INT NOT NULL,
  `STU_reference_Id_stu` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  PRIMARY KEY (`Id`, `Saber_reference_Id_stu`, `Hours of dedication_IDHours Internet-Reading`, `EducationalCenters_id`, `Probes_references_idProbes_references`, `STU_reference_Id_stu`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Stu_hours_reading_influence_Saber_reference1_idx` (`Saber_reference_Id_stu` ASC) VISIBLE,
  INDEX `fk_Stu_hours_reading_influence_Hours of dedication1_idx` (`Hours of dedication_IDHours Internet-Reading` ASC) VISIBLE,
  INDEX `fk_Stu_hours_reading_influence_EducationalCenters1_idx` (`EducationalCenters_id` ASC) VISIBLE,
  INDEX `fk_Stu_hours_reading_influence_Probes_references1_idx` (`Probes_references_idProbes_references` ASC) VISIBLE,
  INDEX `fk_Stu_hours_reading_influence_STU_reference1_idx` (`STU_reference_Id_stu` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  CONSTRAINT `fk_Stu_hours_reading_influence_Saber_reference1`
    FOREIGN KEY (`Saber_reference_Id_stu`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`Id_stu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_hours_reading_influence_Hours of dedication1`
    FOREIGN KEY (`Hours of dedication_IDHours Internet-Reading`)
    REFERENCES `Cultural_violence`.`Hours_of_ dedication` (`IDHours Internet-Reading`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_hours_reading_influence_EducationalCenters1`
    FOREIGN KEY (`EducationalCenters_id`)
    REFERENCES `RelationsAndConclusions`.`EducationalCenters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_hours_reading_influence_Probes_references1`
    FOREIGN KEY (`Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_hours_reading_influence_STU_reference1`
    FOREIGN KEY (`STU_reference_Id_stu` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`Id_stu` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Stu_mother_educational_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_mother_educational_level` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_mother_educational_level` (
  `ID` INT NOT NULL,
  `id_Stu` INT NOT NULL,
  `EducationalCenters_id` INT NOT NULL,
  `Educational-Level_idEducational-Level` INT NOT NULL,
  `Probes_references_idProbes_references` INT NOT NULL,
  PRIMARY KEY (`id_Stu`, `EducationalCenters_id`, `Educational-Level_idEducational-Level`, `ID`, `Probes_references_idProbes_references`),
  INDEX `fk_Stu_mother_educational_level_EducationalCenters1_idx` (`EducationalCenters_id` ASC) VISIBLE,
  INDEX `fk_Stu_mother_educational_level_Educational-Level1_idx` (`Educational-Level_idEducational-Level` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Stu_mother_educational_level_Probes_references1_idx` (`Probes_references_idProbes_references` ASC) VISIBLE,
  CONSTRAINT `fk_Stu_mother_educational_level_Saber_reference1`
    FOREIGN KEY (`id_Stu`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`Id_stu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_mother_educational_level_EducationalCenters1`
    FOREIGN KEY (`EducationalCenters_id`)
    REFERENCES `RelationsAndConclusions`.`EducationalCenters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_mother_educational_level_Educational-Level1`
    FOREIGN KEY (`Educational-Level_idEducational-Level`)
    REFERENCES `Cultural_violence`.`Educational-Level` (`idEducational-Level`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_mother_educational_level_Probes_references1`
    FOREIGN KEY (`Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`VULNERABLE_GROUPS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`VULNERABLE_GROUPS` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`VULNERABLE_GROUPS` (
  `idVULNERABLE_GROUPS` INT NOT NULL,
  `VULNERABLE_GROUPScol` VARCHAR(45) NULL,
  PRIMARY KEY (`idVULNERABLE_GROUPS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cultural_violence`.`VulnerableGroupsHomicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`VulnerableGroupsHomicideViolence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`VulnerableGroupsHomicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `PopulationInformation_id` INT NOT NULL,
  `PopulationInformation_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `PopulationInformation_id1` INT NOT NULL,
  `VULNERABLE_GROUPS_idVULNERABLE_GROUPS` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  `Ind_VulnerableGroupsHomicideViolence` DOUBLE NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `PopulationInformation_id`, `PopulationInformation_Municipalitie_Information_Municipalities_id`, `PopulationInformation_id1`, `VULNERABLE_GROUPS_idVULNERABLE_GROUPS`, `YEARS_idYEARS`),
  INDEX `fk_VulnerableGroupsHomicideViolence_Municipalitie_Informati_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_VulnerableGroupsHomicideViolence_PopulationInformation1_idx` (`PopulationInformation_id` ASC, `PopulationInformation_Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_VulnerableGroupsHomicideViolence_PopulationInformation2_idx` (`PopulationInformation_id1` ASC) VISIBLE,
  INDEX `fk_VulnerableGroupsHomicideViolence_VULNERABLE_GROUPS1_idx` (`VULNERABLE_GROUPS_idVULNERABLE_GROUPS` ASC) VISIBLE,
  INDEX `fk_VulnerableGroupsHomicideViolence_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  CONSTRAINT `fk_VulnerableGroupsHomicideViolence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VulnerableGroupsHomicideViolence_PopulationInformation1`
    FOREIGN KEY (`PopulationInformation_id` , `PopulationInformation_Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id` , `Municipalitie_Information_Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VulnerableGroupsHomicideViolence_PopulationInformation2`
    FOREIGN KEY (`PopulationInformation_id1`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VulnerableGroupsHomicideViolence_VULNERABLE_GROUPS1`
    FOREIGN KEY (`VULNERABLE_GROUPS_idVULNERABLE_GROUPS`)
    REFERENCES `Cultural_violence`.`VULNERABLE_GROUPS` (`idVULNERABLE_GROUPS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VulnerableGroupsHomicideViolence_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`VulnerableGroupsSuicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`VulnerableGroupsSuicideViolence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`VulnerableGroupsSuicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `occurrences` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `VULNERABLE_GROUPS_idVULNERABLE_GROUPS` INT NOT NULL,
  `PopulationInformation_id` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  `subin_vulnerable_groups_suicide` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `VULNERABLE_GROUPS_idVULNERABLE_GROUPS`, `PopulationInformation_id`, `YEARS_idYEARS`),
  INDEX `Iindxsubin_vulnerable_groups_suicide` (`subin_vulnerable_groups_suicide` ASC) VISIBLE,
  INDEX `fk_VulnerableGroupsSuicideViolence_Municipalitie_Informatio_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_VulnerableGroupsSuicideViolence_VULNERABLE_GROUPS1_idx` (`VULNERABLE_GROUPS_idVULNERABLE_GROUPS` ASC) VISIBLE,
  INDEX `fk_VulnerableGroupsSuicideViolence_PopulationInformation1_idx` (`PopulationInformation_id` ASC) VISIBLE,
  INDEX `fk_VulnerableGroupsSuicideViolence_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  CONSTRAINT `fk_VulnerableGroupsSuicideViolence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VulnerableGroupsSuicideViolence_VULNERABLE_GROUPS1`
    FOREIGN KEY (`VULNERABLE_GROUPS_idVULNERABLE_GROUPS`)
    REFERENCES `Cultural_violence`.`VULNERABLE_GROUPS` (`idVULNERABLE_GROUPS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VulnerableGroupsSuicideViolence_PopulationInformation1`
    FOREIGN KEY (`PopulationInformation_id`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VulnerableGroupsSuicideViolence_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`stu_haveEthnia_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`stu_haveEthnia_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`stu_haveEthnia_influence` (
  `ID` INT NOT NULL,
  `Saber_reference_Id_stu` INT NOT NULL,
  `EducationalCenters_id` INT NOT NULL,
  `have_Ethia` TINYINT NULL,
  `Probes_references_idProbes_references` INT NOT NULL,
  `STU_reference_Id_stu` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  PRIMARY KEY (`ID`, `Saber_reference_Id_stu`, `EducationalCenters_id`, `Probes_references_idProbes_references`, `STU_reference_Id_stu`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`, `YEARS_idYEARS`),
  INDEX `fk_stu_haveEthnia_influence_EducationalCenters1_idx` (`EducationalCenters_id` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_stu_haveEthnia_influence_Saber_reference1_idx` (`Saber_reference_Id_stu` ASC) VISIBLE,
  INDEX `fk_stu_haveEthnia_influence_Probes_references1_idx` (`Probes_references_idProbes_references` ASC) VISIBLE,
  INDEX `fk_stu_haveEthnia_influence_STU_reference1_idx` (`STU_reference_Id_stu` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  INDEX `fk_stu_haveEthnia_influence_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  CONSTRAINT `fk_stu_haveEthnia_influence_Saber_reference1`
    FOREIGN KEY (`Saber_reference_Id_stu`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`Id_stu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_haveEthnia_influence_EducationalCenters1`
    FOREIGN KEY (`EducationalCenters_id`)
    REFERENCES `RelationsAndConclusions`.`EducationalCenters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_haveEthnia_influence_Probes_references1`
    FOREIGN KEY (`Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_haveEthnia_influence_STU_reference1`
    FOREIGN KEY (`STU_reference_Id_stu` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`Id_stu` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_haveEthnia_influence_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`stu_haveInternet_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`stu_haveInternet_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`stu_haveInternet_influence` (
  `ID` INT NOT NULL,
  `EducationalCenters_id` INT NOT NULL,
  `have_Internet` TINYINT NULL,
  `Probes_references_idProbes_references1` INT NOT NULL,
  `STU_reference_Id_stu` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  PRIMARY KEY (`ID`, `EducationalCenters_id`, `Probes_references_idProbes_references1`, `STU_reference_Id_stu`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`, `YEARS_idYEARS`),
  INDEX `fk_stu_haveInternet_influence_EducationalCenters1_idx` (`EducationalCenters_id` ASC) VISIBLE,
  INDEX `fk_stu_haveInternet_influence_Probes_references1_idx` (`Probes_references_idProbes_references1` ASC) VISIBLE,
  INDEX `fk_stu_haveInternet_influence_STU_reference1_idx` (`STU_reference_Id_stu` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  INDEX `fk_stu_haveInternet_influence_YEARS1_idx` (`YEARS_idYEARS` ASC) VISIBLE,
  CONSTRAINT `fk_stu_haveInternet_influence_EducationalCenters1`
    FOREIGN KEY (`EducationalCenters_id`)
    REFERENCES `RelationsAndConclusions`.`EducationalCenters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_haveInternet_influence_Probes_references1`
    FOREIGN KEY (`Probes_references_idProbes_references1`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_haveInternet_influence_STU_reference1`
    FOREIGN KEY (`STU_reference_Id_stu` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`Id_stu` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_haveInternet_influence_YEARS1`
    FOREIGN KEY (`YEARS_idYEARS`)
    REFERENCES `RelationsAndConclusions`.`YEARS` (`idYEARS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `GENDER_VIOLENCE` ;

-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`DomesticViolenceNonGenderBAsedRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`DomesticViolenceNonGenderBAsedRate` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`DomesticViolenceNonGenderBAsedRate` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `domestic_violence_rate_per_100k` INT NULL DEFAULT NULL,
  `subin_domestic_violence` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`DomesticViolenceRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`DomesticViolenceRate` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`DomesticViolenceRate` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `gender_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `domestic_violence_rate_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_domestic_violence` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`GenderHomicideRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderHomicideRate` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderHomicideRate` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `gender_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `homicide_rate_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_gender_homicide` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`GenderInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderInformation` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderInformation` (
  `id` INT NULL DEFAULT NULL,
  `gender_name` VARCHAR(255) NULL DEFAULT NULL,
  `Municipalities_id` FLOAT NULL DEFAULT NULL,
  `population_by_gender` FLOAT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`GenderViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderViolenceIndex` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderViolenceIndex` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `subin_partner_homicide` FLOAT NULL DEFAULT NULL,
  `subin_romantic_suicide` FLOAT NULL DEFAULT NULL,
  `subin_vulnerability_homicide` FLOAT NULL DEFAULT NULL,
  `subin_vulnerability_suicide` FLOAT NULL DEFAULT NULL,
  `subin_gender_homicide` FLOAT NULL DEFAULT NULL,
  `subin_domestic_violence` FLOAT NULL DEFAULT NULL,
  `gender_violence_index` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`GenderVulnerabilityHomicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderVulnerabilityHomicideViolence` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderVulnerabilityHomicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `vulnerability_factor_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `homicide_rate_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_vulnerability_homicide` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`GenderVulnerabilitySuicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderVulnerabilitySuicideViolence` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderVulnerabilitySuicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `vulnerability_factor_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `suicide_rate_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_vulnerability_suicide` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`IcfesResultsAnalysis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`IcfesResultsAnalysis` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`IcfesResultsAnalysis` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `gender_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `average_math_score` FLOAT NULL DEFAULT NULL,
  `average_natural_sciences_score` FLOAT NULL DEFAULT NULL,
  `average_social_and_citizenship_score` FLOAT NULL DEFAULT NULL,
  `average_languages_score` FLOAT NULL DEFAULT NULL,
  `average_foreign_language_score` FLOAT NULL DEFAULT NULL,
  `average_global_score` FLOAT NULL DEFAULT NULL,
  `subin_global_score` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`PartnerHomicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`PartnerHomicideViolence` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`PartnerHomicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `gender_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `homicide_rate_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_partner_homicide` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`RomanticSuicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`RomanticSuicideViolence` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`RomanticSuicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `gender_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `suicide_rate_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_romantic_suicide` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

USE `Structural_Violence` ;

-- -----------------------------------------------------
-- Table `Structural_Violence`.`CarOwnership_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`CarOwnership_influence` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`CarOwnership_influence` (
  `id` INT NULL DEFAULT NULL,
  `municipality_id` INT NULL DEFAULT NULL,
  `date_of_test` DATE NULL DEFAULT NULL,
  `count_cases_true` INT NULL DEFAULT NULL,
  `count_cases_false` INT NULL DEFAULT NULL,
  `subin_carOwnership` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`CarOwnershipcases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`CarOwnershipcases` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`CarOwnershipcases` (
  `id` INT NULL DEFAULT NULL,
  `date_of_test` DATE NULL DEFAULT NULL,
  `municipality_id` INT NULL DEFAULT NULL,
  `carOwnershipcases` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`EducationAccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`EducationAccess` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`EducationAccess` (
  `id` INT NULL DEFAULT NULL,
  `municipality_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `basic_education_centers_per_100k` FLOAT NULL DEFAULT NULL,
  `middle_education_centers_per_100k` FLOAT NULL DEFAULT NULL,
  `technical_professional_centers_per_100k` FLOAT NULL DEFAULT NULL,
  `university_centers_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_education` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`FloorType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`FloorType` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`FloorType` (
  `id` INT NULL DEFAULT NULL,
  `FloorType` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`FloorType_Municipalities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`FloorType_Municipalities` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`FloorType_Municipalities` (
  `id` INT NULL DEFAULT NULL,
  `date_of_test` DATE NULL DEFAULT NULL,
  `municipality_id` INT NULL DEFAULT NULL,
  `FloorType` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`FloorType_subindicator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`FloorType_subindicator` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`FloorType_subindicator` (
  `id` INT NULL DEFAULT NULL,
  `municipality_id` INT NULL DEFAULT NULL,
  `case` INT NULL DEFAULT NULL,
  `count_case` INT NULL DEFAULT NULL,
  `FloorType_subindicator` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`HealthAccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`HealthAccess` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`HealthAccess` (
  `id` INT NULL DEFAULT NULL,
  `municipality_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `first_level_centers_per_100k` FLOAT NULL DEFAULT NULL,
  `second_level_centers_per_100k` FLOAT NULL DEFAULT NULL,
  `third_level_centers_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_health` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`HealthCenters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`HealthCenters` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`HealthCenters` (
  `id` INT NULL DEFAULT NULL,
  `health_center_id` INT NULL DEFAULT NULL,
  `health_center_name` VARCHAR(255) NULL DEFAULT NULL,
  `care_level` VARCHAR(255) NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`health_center_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`Health_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`Health_level` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`Health_level` (
  `Id` INT NULL DEFAULT NULL,
  `Healt_level_level` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`Inequality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`Inequality` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`Inequality` (
  `municipality_id` INT NULL DEFAULT NULL,
  `gini_index` FLOAT NULL DEFAULT NULL);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`Poverty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`Poverty` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`Poverty` (
  `municipality_id` INT NULL DEFAULT NULL,
  `multidimensional_poverty_index` FLOAT NULL DEFAULT NULL,
  `monetary_poverty_index` FLOAT NULL DEFAULT NULL,
  `extreme_monetary_poverty_index` FLOAT NULL DEFAULT NULL,
  `unsatisfied_basic_needs_index` FLOAT NULL DEFAULT NULL,
  `subin_poverty` FLOAT NULL DEFAULT NULL);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`RoomPerBedroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`RoomPerBedroom` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`RoomPerBedroom` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `measurement` INT NULL DEFAULT NULL,
  `subin_room_per_bedroom` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`StructuralViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`StructuralViolenceIndex` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`StructuralViolenceIndex` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `subin_education_access` FLOAT NULL DEFAULT NULL,
  `subin_health_access` FLOAT NULL DEFAULT NULL,
  `subin_inequality` FLOAT NULL DEFAULT NULL,
  `subin_poverty` FLOAT NULL DEFAULT NULL,
  `subin_structural_influencers` FLOAT NULL DEFAULT NULL,
  `structural_violence_index` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`VidegamesconsoleOwnership_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`VidegamesconsoleOwnership_influence` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`VidegamesconsoleOwnership_influence` (
  `id` INT NULL DEFAULT NULL,
  `municipality_id` INT NULL DEFAULT NULL,
  `date_of_test` DATE NULL DEFAULT NULL,
  `count_cases_true` INT NULL DEFAULT NULL,
  `count_cases_false` INT NULL DEFAULT NULL,
  `subin_VidegamesconsoleOwnership` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`VidegamesconsoleOwnershipcases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`VidegamesconsoleOwnershipcases` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`VidegamesconsoleOwnershipcases` (
  `id` INT NULL DEFAULT NULL,
  `date_of_test` DATE NULL DEFAULT NULL,
  `municipality_id` INT NULL DEFAULT NULL,
  `VidegamesconsoleOwnershipcases` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`WashingMachineOwnership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`WashingMachineOwnership` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`WashingMachineOwnership` (
  `id` INT NULL DEFAULT NULL,
  `date_of_test` DATE NULL DEFAULT NULL,
  `municipality_id` INT NULL DEFAULT NULL,
  `WashingMachineOwnershipcases` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`WashingMachineOwnership_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`WashingMachineOwnership_influence` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`WashingMachineOwnership_influence` (
  `id` INT NULL DEFAULT NULL,
  `municipality_id` INT NULL DEFAULT NULL,
  `date_of_test` DATE NULL DEFAULT NULL,
  `count_cases_true` INT NULL DEFAULT NULL,
  `count_cases_false` INT NULL DEFAULT NULL,
  `subin_washing_machine` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`WorkHours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`WorkHours` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`WorkHours` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `measurement` INT NULL DEFAULT NULL,
  `subin_work_hours` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`WorkStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`WorkStatus` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`WorkStatus` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `measurement` TINYINT NULL DEFAULT NULL,
  `subin_work_status` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Structural_Violence`.`structutural_influencers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`structutural_influencers` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`structutural_influencers` (
  `id` INT NULL DEFAULT NULL,
  `subin_room_per_bedroom` FLOAT NULL DEFAULT NULL,
  `subin_videgames_console` FLOAT NULL DEFAULT NULL,
  `subin_work_status` FLOAT NULL DEFAULT NULL,
  `subin_work_hours` FLOAT NULL DEFAULT NULL,
  `subin_washing_machine` FLOAT NULL DEFAULT NULL,
  `subin_floor_type` FLOAT NULL DEFAULT NULL,
  `subin_Internet_access` FLOAT NULL DEFAULT NULL,
  `subin_stuctural_influencers` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

USE `Phisical_violence` ;

-- -----------------------------------------------------
-- Table `Phisical_violence`.`FinalViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`FinalViolenceIndex` ;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`FinalViolenceIndex` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `subin_structural_violence` INT NULL DEFAULT NULL,
  `subin_cultural_violence` INT NULL DEFAULT NULL,
  `subin_gender_violence` INT NULL DEFAULT NULL,
  `subin_physical_violence` INT NULL DEFAULT NULL,
  `final_violence_index` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Phisical_violence`.`HomicideRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`HomicideRate` ;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`HomicideRate` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `homicide_rate_per_100k` INT NULL DEFAULT NULL,
  `subin_homicide` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Phisical_violence`.`PhysicalViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`PhysicalViolenceIndex` ;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`PhysicalViolenceIndex` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `subin_homicide` INT NULL DEFAULT NULL,
  `subin_suicide` INT NULL DEFAULT NULL,
  `subin_domestic_violence` INT NULL DEFAULT NULL,
  `subin_violence_against_children_and_youth` INT NULL DEFAULT NULL,
  `subin_child_abuse` INT NULL DEFAULT NULL,
  `physical_violence_index` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Phisical_violence`.`PhysicalViolenceInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`PhysicalViolenceInformation` ;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`PhysicalViolenceInformation` (
  `id` INT NULL DEFAULT NULL,
  `physical_violence_type` VARCHAR(255) NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Phisical_violence`.`SuicideRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`SuicideRate` ;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`SuicideRate` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `suicide_rate_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_suicide` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Phisical_violence`.`ViolenceAgainstChildrenAndYouth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`ViolenceAgainstChildrenAndYouth` ;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`ViolenceAgainstChildrenAndYouth` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `violence_against_children_and_youth_rate_per_100k` INT NULL DEFAULT NULL,
  `subin_violence_against_children_and_youth` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

USE `Cultural_violence` ;

-- -----------------------------------------------------
-- procedure Count_ethnic_influencer
-- -----------------------------------------------------

USE `Cultural_violence`;
DROP procedure IF EXISTS `Cultural_violence`.`Count_ethnic_influencer`;

DELIMITER $$
USE `Cultural_violence`$$
CREATE PROCEDURE `Count_ethnic_influencer` ()
BEGIN
CREATE EVENT update_ethnic_influencer
ON SCHEDULE EVERY 1 DAY
STARTS CURRENT_DATE
DO
    UPDATE 
        Cultural_violence.ethnic_Influencer
    SET 
        count_have_ethnia = (
            SELECT 
                COUNT(Cultural_violence.stu_haveEthnia_influence.haveethnia)
            FROM 
                Cultural_violence.stu_haveEthnia_influence
            INNER JOIN 
                RelationsAndConclusions.STU_reference 
            ON 
                Cultural_violence.stu_haveEthnia_influence.STU_reference_Id_stu = RelationsAndConclusions.STU_reference.Id_stu
            INNER JOIN 
                RelationsAndConclusions.Probes_references 
            ON 
                RelationsAndConclusions.STU_reference.Probes_references_IdProbes_references = RelationsAndConclusions.Probes_references.idProbes_references
            WHERE 
                RelationsAndConclusions.Probes_references.Year = Cultural_violence.ethnic_Influencer.Year
                AND RelationsAndConclusions.STU_reference.Municipalitie_information_Municipalities_id = Cultural_violence.ethnic_Influencer.Municipalitie_Information_Municipalities_id
                AND Cultural_violence.stu_haveEthnia_influence.haveethnia = TRUE
        );


END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
