-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 22:16:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RelationsAndConclusions
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `RelationsAndConclusions` ;

-- -----------------------------------------------------
-- Schema RelationsAndConclusions
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RelationsAndConclusions` ;
-- -----------------------------------------------------
-- Schema Cultural_violence
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Cultural_violence` ;

-- -----------------------------------------------------
-- Schema Cultural_violence
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cultural_violence` ;
-- -----------------------------------------------------
-- Schema GENDER_VIOLENCE
-- -----------------------------------------------------
-- 	
DROP SCHEMA IF EXISTS `GENDER_VIOLENCE` ;

-- -----------------------------------------------------
-- Schema GENDER_VIOLENCE
--
-- 	
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GENDER_VIOLENCE` ;
-- -----------------------------------------------------
-- Schema Structural_Violence
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Structural_Violence` ;

-- -----------------------------------------------------
-- Schema Structural_Violence
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Structural_Violence` ;
-- -----------------------------------------------------
-- Schema Phisical_violence
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Phisical_violence` ;

-- -----------------------------------------------------
-- Schema Phisical_violence
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Phisical_violence` ;
USE `RelationsAndConclusions` ;

-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`FinalViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`FinalViolenceIndex`;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`FinalViolenceIndex` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `municipality_id` INT,
    `year` YEAR,
    `subin_structural` INT,
    `subin_cultural` INT,
    `subin_gender` INT,
    `subin_physical` INT,
    `final_violence_index` INT
);

-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`EducationalCenters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`EducationalCenters` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`EducationalCenters` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `educational_center_id` INT NOT NULL,
    `educational_center_name` VARCHAR(255) NULL DEFAULT NULL,
    `teaching_level` INT NULL DEFAULT NULL,
    `Municipalitie_Information_Municipalities_id` INT NOT NULL,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);


-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`Municipalitie_Information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`Municipalitie_Information` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`Municipalitie_Information` (
    `id` INT NOT NULL PRIMARY KEY,
    `Municipalitie_name` VARCHAR(45) NOT NULL,
    `Department_name` VARCHAR(45) NOT NULL,
    `ID_Deparment` INT NOT NULL
);



-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`PopulationInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`PopulationInformation` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`PopulationInformation` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `year` YEAR(4) NOT NULL,
    `Municipalitie_Information_Municipalities_id` INT NOT NULL,
    `population` INT NULL DEFAULT NULL,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`Probes_references`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`Probes_references` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`Probes_references` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Date` DATE NULL,
    `People_Who_takes_probes` INT NULL
);
  

-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`STU_reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`STU_reference` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`STU_reference` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `ID_Student` VARCHAR(45) NULL,
    `EducationalCenters_id` INT NOT NULL,
    `Municipalitie_Information_Municipalities_id` INT NOT NULL,
    `Probes_references_idProbes_references` INT NOT NULL,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`),
    FOREIGN KEY (`EducationalCenters_id`)
        REFERENCES `RelationsAndConclusions`.`EducationalCenters` (`id`),
    FOREIGN KEY (`Probes_references_idProbes_references`)
        REFERENCES `RelationsAndConclusions`.`Probes_references` (`id`)
);

USE `Cultural_violence` ;

-- -----------------------------------------------------
-- Table `Cultural_violence`.`Books_for_Family_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Books_for_Family_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Books_for_Family_influence` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `year` YEAR(4) NOT NULL,
    `municipality_id` INT NOT NULL,
    `book_indicator` INT NULL DEFAULT NULL,
    FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);
  
-- -----------------------------------------------------
-- Table `Cultural_violence`.`CulturalInfluence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`CulturalInfluence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`CulturalInfluence` (
    `Id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Municipalitie_Information_Municipalities_id` INT NOT NULL,
    `Year` YEAR(4) NULL,
    `ethnic_Influencer_indicator` DECIMAL NOT NULL,
    `books_for_family_indicator` DECIMAL NOT NULL,
    `Stu_internet_influence_indicator` DECIMAL NOT NULL,
    `Stu_read_for_pleasure_indicator` DECIMAL NOT NULL,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Cultural_violence`.`Father_Educational_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Father_Educational_information` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Father_Educational_information` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Municipalitie_Information_Municipalities_id` INT NOT NULL,
    `Year` YEAR(4) NULL,
    `Father_Educational_influence` DECIMAL(2) NULL,
    CONSTRAINT `fk_Father_Educational_influence_Municipalitie_Information1` FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Cultural_violence`.`Hours_of_Reading_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Hours_of_Reading_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Hours_of_Reading_influence` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Municipalitie_Information_Municipalities_id` INT NOT NULL,
    `Year` YEAR(4) NULL,
    `Hours_of_reading_indicator` DOUBLE,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Cultural_violence`.`InternetAccess_influennce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`InternetAccess_influennce` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`InternetAccess_influennce` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `municipaliti_ratio_Internet_acces` INT NOT NULL,
    `Municipalities_id` INT NOT NULL, 
    `Hours_of_internet_indicator` DOUBLE,
    FOREIGN KEY (`Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Cultural_violence`.`InternetAccess_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`InternetAccess_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`InternetAccess_influence` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Municipalitie_Information_Municipalities_id` INT NOT NULL,
    `year` YEAR(4) NULL,
    `count_cases_true` INT NULL DEFAULT NULL,
    `subin_Internet_access` FLOAT NULL DEFAULT NULL,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Cultural_violence`.`Interpersonal_Conflicts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Interpersonal_Conflicts` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Interpersonal_Conflicts` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Year` YEAR(4) NULL,
    `PopulationInformation_id` INT NOT NULL,
    `occurrences` INT NULL DEFAULT NULL,
    `subin_Interpersonal_conflicts` FLOAT NULL DEFAULT NULL,
    FOREIGN KEY (`PopulationInformation_id`)
        REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`)
);

-- -----------------------------------------------------
-- Table `Cultural_violence`.`Interpersonal_Homicide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Interpersonal_Homicide` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Interpersonal_Homicide` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `PopulationInformation_id` INT NOT NULL,
    `YEARS` YEAR(4) NOT NULL,
    `occurrences` INT NULL DEFAULT NULL,
    `subin_vulnerable_groups_homicide` FLOAT,
    FOREIGN KEY (`PopulationInformation_id`)
        REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`)
);

-- -----------------------------------------------------
-- Table `Cultural_violence`.`Mother_Educational_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Mother_Educational_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Mother_Educational_influence` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `municipalitie_id` INT NOT NULL,
    `mother_educational_influence` FLOAT NOT NULL,
    FOREIGN KEY (`municipalitie_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Cultural_violence`.`RACIAL_ANC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`RACIAL_ANC` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`RACIAL_ANC` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Name` VARCHAR(45) NULL
);
  
-- -----------------------------------------------------
-- Table `Cultural_violence`.`RacialAncestryHomicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`RacialAncestryHomicideViolence`;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`RacialAncestryHomicideViolence` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `municipality_id` INT NOT NULL,
    `population_id` INT NOT NULL,
    `racial_anc_id` INT NOT NULL,
    `year_id` INT NOT NULL,
    `occurrences` INT NULL DEFAULT NULL,
    FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`),
    FOREIGN KEY (`population_id`)
        REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`),
    FOREIGN KEY (`racial_anc_id`)
        REFERENCES `Cultural_violence`.`RACIAL_ANC` (`id`)
);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`RacialAncestrySuicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`RacialAncestrySuicideViolence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`RacialAncestrySuicideViolence` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `racial_anc_id` INT NOT NULL,
    `municipality_id` INT NOT NULL,
    `population_id` INT NOT NULL,
    `year` YEAR(4) NULL,
    `occurrences` INT NULL DEFAULT NULL,
    FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`),
    FOREIGN KEY (`population_id`)
        REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`),
    FOREIGN KEY (`racial_anc_id`)
        REFERENCES `Cultural_violence`.`RACIAL_ANC` (`id`)
);

-- -----------------------------------------------------
-- Table `Cultural_violence`.`SociopoliticHomicide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`SociopoliticHomicide` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`SociopoliticHomicide` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `population_id` INT NOT NULL,
    `municipality_id` INT NOT NULL,
    `cases` VARCHAR(45) NULL,
    FOREIGN KEY (`population_id`)
        REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`),
    FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Cultural_violence`.`Stu_Father_educational_Level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_Father_educational_Level` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_Father_educational_Level` (
    `Id` INT NOT NULL PRIMARY KEY,
    `stu_ref_id` INT NOT NULL,
     `father_edu_level` INT NULL,
    FOREIGN KEY (`stu_ref_id`)
        REFERENCES `RelationsAndConclusions`.`STU_reference` (`id`)
	);

-- -----------------------------------------------------
-- Table `Cultural_violence`.`Stu_books_for_Family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_books_for_Family`;
CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_books_for_Family` (
    `id` INT NOT NULL PRIMARY KEY,
    `stu_ref_id` INT NOT NULL,
    `books_for_family` INT NULL,
    FOREIGN KEY (`stu_ref_id`)
        REFERENCES `RelationsAndConclusions`.`STU_reference` (`id`)
);

-- Table `Cultural_violence`.`Stu_hours_Internet_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_hours_Internet_influence`;
CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_hours_Internet_influence` (
    `id` INT NOT NULL PRIMARY KEY,
    `stu_ref_id` INT NOT NULL,
    `hours_of_dedication` INT NULL,
    FOREIGN KEY (`stu_ref_id`)
        REFERENCES `RelationsAndConclusions`.`STU_reference` (`id`)
);

-- Table `Cultural_violence`.`Stu_hours_reading_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_hours_reading_influence`;
CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_hours_reading_influence` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `stu_ref_id` INT NOT NULL,
    `hours_of_dedication` INT NULL,
    `year` YEAR(4) NOT NULL,
    FOREIGN KEY (`stu_ref_id`)
        REFERENCES `RelationsAndConclusions`.`STU_reference` (`id`)
);

-- Table `Cultural_violence`.`Stu_mother_educational_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_mother_educational_level`;
CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_mother_educational_level` (
    `id` INT NOT NULL PRIMARY KEY,
    `stu_ref_id` INT NOT NULL,
    `mother_edu_level` INT NULL,
    FOREIGN KEY (`stu_ref_id`)
        REFERENCES `RelationsAndConclusions`.`STU_reference` (`id`)
);

-- Table `Cultural_violence`.`VULNERABLE_GROUPS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`VULNERABLE_GROUPS`;
CREATE TABLE IF NOT EXISTS `Cultural_violence`.`VULNERABLE_GROUPS` (
    `id` INT NOT NULL PRIMARY KEY,
    `group_name` VARCHAR(45) NULL
);

-- Table `Cultural_violence`.`VulnerableGroupsHomicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`VulnerableGroupsHomicideViolence`;
CREATE TABLE IF NOT EXISTS `Cultural_violence`.`VulnerableGroupsHomicideViolence` (
    `id` INT NOT NULL PRIMARY KEY,
    `pop_info_id` INT NOT NULL,
    `vulnerable_group_id` INT NOT NULL,
    `year` YEAR(4) NULL,
    `cases` INT NULL,
    `indicator` DECIMAL(2) NULL,
    FOREIGN KEY (`pop_info_id`)
        REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`),
    FOREIGN KEY (`vulnerable_group_id`)
        REFERENCES `Cultural_violence`.`VULNERABLE_GROUPS` (`id`)
);
-- Table `Cultural_violence`.`CulturalViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`CulturalViolenceIndex`;
CREATE TABLE IF NOT EXISTS `Cultural_violence`.`CulturalViolenceIndex` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `municipality_id` INT NOT NULL,
    `year` YEAR(4) NULL,
    `subin_ancestry_homicide` FLOAT NOT NULL,
    `subin_ancestry_suicide` FLOAT NOT NULL,
    `subin_vulnerable_groups_homicide` FLOAT NOT NULL,
    `subin_vulnerability_suicide` FLOAT NOT NULL,
    `context_violence_index` FLOAT NOT NULL,
    FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- Table `Cultural_violence`.`VulnerableGroupsSuicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`VulnerableGroupsSuicideViolence`;
CREATE TABLE IF NOT EXISTS `Cultural_violence`.`VulnerableGroupsSuicideViolence` (
    `id` INT NOT NULL PRIMARY KEY,
    `vulnerable_group_id` INT NOT NULL,
    `pop_info_id` INT NOT NULL,
    `occurrences` INT NULL,
    `subin_vulnerable_groups_suicide` FLOAT NULL,
     FOREIGN KEY (`pop_info_id`)
        REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`),
    FOREIGN KEY (`vulnerable_group_id`)
        REFERENCES `Cultural_violence`.`VULNERABLE_GROUPS` (`id`)
);

-- Table `Cultural_violence`.`gender(Victim)`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`gender(Victim)`;
CREATE TABLE IF NOT EXISTS `Cultural_violence`.`gender(Victim)` (
    `id` INT NOT NULL PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL
);

-- Table `Cultural_violence`.`stu_haveEthnia_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`stu_haveEthnia_influence`;
CREATE TABLE IF NOT EXISTS `Cultural_violence`.`stu_haveEthnia_influence` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `stu_ref_id` INT NOT NULL,
    `probe_ref_id` INT NOT NULL,
    `year` YEAR(4) NOT NULL,
    `have_ethnia` TINYINT NULL,
    FOREIGN KEY (`stu_ref_id`)
        REFERENCES `RelationsAndConclusions`.`STU_reference` (`id`),
    FOREIGN KEY (`probe_ref_id`)
        REFERENCES `RelationsAndConclusions`.`Probes_references` (`id`)
);

-- Table `Cultural_violence`.`stu_haveInternet_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`stu_haveInternet_influence`;
CREATE TABLE IF NOT EXISTS `Cultural_violence`.`stu_haveInternet_influence` (
    `id` INT NOT NULL PRIMARY KEY,
    `have_internet` TINYINT NULL,
    `stu_ref_id` INT NOT NULL,
    FOREIGN KEY (`stu_ref_id`)
        REFERENCES `RelationsAndConclusions`.`STU_reference` (`id`)
);

-- Table `GENDER_VIOLENCE`.`DomesticViolenceNonGenderBAsedRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`DomesticViolenceNonGenderBAsedRate`;
CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`DomesticViolenceNonGenderBAsedRate` (
    `id` INT NOT NULL PRIMARY KEY,
    `municipality_id` INT NOT NULL,
    `year` YEAR(4) NULL,
    `cases` INT NULL,
    `domestic_violence_rate_per_100k` FLOAT NULL,
    `subin_domestic_violence` FLOAT NULL,
    FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- Table `GENDER_VIOLENCE`.`DomesticViolenceRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`DomesticViolenceRate`;
CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`DomesticViolenceRate` (
    `id` INT NOT NULL PRIMARY KEY,
    `municipality_id` INT NOT NULL,
    `gender_victim_id` INT NOT NULL,
    `year` YEAR(4) NULL,
    `cases` INT NULL,
    `domestic_violence_rate_per_100k` FLOAT NULL,
    `subin_domestic_violence` FLOAT NULL,
    FOREIGN KEY (`gender_victim_id`)
        REFERENCES `Cultural_violence`.`gender(Victim)` (`id`),
    FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- Table `GENDER_VIOLENCE`.`GenderHomicideRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderHomicideRate`;
CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderHomicideRate` (
    `id` INT NOT NULL PRIMARY KEY,
    `gender_id` INT NOT NULL,
    `municipality_id` INT NOT NULL,
    `year` YEAR(4) NULL,
    `cases` INT NULL,
    `homicide_rate_per_100k` FLOAT NULL,
    `subin_gender_homicide` FLOAT NULL,
    FOREIGN KEY (`gender_id`)
        REFERENCES `Cultural_violence`.`gender(Victim)` (`id`),
    FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- Table `GENDER_VIOLENCE`.`GenderInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderInformation`;
CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderInformation` (
    `id` INT NOT NULL PRIMARY KEY,
    `municipality_id` INT NOT NULL,
    `gender_name` VARCHAR(255) NULL,
    `population_by_gender` FLOAT NULL,
    `year` YEAR(4) NULL,
    FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- Table `GENDER_VIOLENCE`.`GenderViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderViolenceIndex`;
CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderViolenceIndex` (
    `id` INT NOT NULL PRIMARY KEY,
    `municipality_id` INT NULL,
    `year` YEAR(4) NULL,
    `subin_partner_homicide` FLOAT NULL,
    `subin_romantic_suicide` FLOAT NULL,
    `subin_vulnerability_homicide` FLOAT NULL,
    `subin_vulnerability_suicide` FLOAT NULL,
    `subin_gender_homicide` FLOAT NULL,
    `subin_domestic_violence` FLOAT NULL,
    `gender_violence_index` FLOAT NULL
);

-- Table `GENDER_VIOLENCE`.`GenderVulnerabilityHomicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderVulnerabilityHomicideViolence`;
CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderVulnerabilityHomicideViolence` (
    `id` INT NOT NULL PRIMARY KEY,
    `municipality_id` INT NULL,
    `vulnerability_factor_id` INT NULL,
    `year` YEAR(4) NULL,
    `cases` INT NULL,
    `homicide_rate_per_100k` FLOAT NULL,
    `subin_vulnerability_homicide` FLOAT NULL
);

-- Table `GENDER_VIOLENCE`.`GenderVulnerabilitySuicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderVulnerabilitySuicideViolence`;
CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderVulnerabilitySuicideViolence` (
    `id` INT NOT NULL PRIMARY KEY,
    `municipality_id` INT NOT NULL,
    `vulnerability_factor_id` INT NULL,
    `year` YEAR(4) NULL,
    `cases` INT NULL,
    `suicide_rate_per_100k` FLOAT NULL,
    `subin_vulnerability_suicide` FLOAT NULL,
    `gender_victim_id` INT NOT NULL,
    FOREIGN KEY (`gender_victim_id`)
        REFERENCES `Cultural_violence`.`gender(Victim)` (`id`),
    FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);
-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`IcfesResultsAnalysis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`IcfesResultsAnalysis`;
CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`IcfesResultsAnalysis` (
    `id` INT PRIMARY KEY,
    `Municipalities_id` INT,
    `gender_id` INT,
    `year` YEAR(4),
    `average_math_score` FLOAT,
    `average_natural_sciences_score` FLOAT,
    `average_social_and_citizenship_score` FLOAT,
    `average_languages_score` FLOAT,
    `average_foreign_language_score` FLOAT,
    `average_global_score` FLOAT,
    `subin_global_score` FLOAT
);

-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`PartnerHomicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`PartnerHomicideViolence`;
CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`PartnerHomicideViolence` (
    `id` INT PRIMARY KEY,
    `year` YEAR(4),
    `cases` INT,
    `homicide_rate_per_100k` FLOAT,
    `subin_partner_homicide` FLOAT,
    `Municipalitie_Information_Municipalities_id` INT,
    `gender(Victim)_id` INT,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`),
    FOREIGN KEY (`gender(Victim)_id`)
        REFERENCES `Cultural_violence`.`gender(Victim)` (`id`)
);

-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`RomanticSuicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`RomanticSuicideViolence`;
CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`RomanticSuicideViolence` (
    `id` INT PRIMARY KEY,
    `Municipalities_id` INT,
    `gender_id` INT,
    `year` YEAR(4),
    `cases` INT,
    `suicide_rate_per_100k` FLOAT,
    `subin_romantic_suicide` FLOAT,
    `Municipalitie_Information_Municipalities_id` INT,
    `gender(Victim)_id` INT,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`),
    FOREIGN KEY (`gender(Victim)_id`)
        REFERENCES `Cultural_violence`.`gender(Victim)` (`id`)
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`CarOwnership_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`CarOwnership_influence`;
CREATE TABLE IF NOT EXISTS `Structural_Violence`.`CarOwnership_influence` (
    `id` INT PRIMARY KEY,
    `Probes_references_id` INT,
    `Municipalitie_Information_Municipalities_id` INT,
    `count_cases_true` INT,
    `count_cases_false` INT,
    `CarOwnership` FLOAT,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`),
    FOREIGN KEY (`Probes_references_id`)
        REFERENCES `RelationsAndConclusions`.`Probes_references` (`id`)
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`EducationAccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`EducationAccess`;
CREATE TABLE IF NOT EXISTS `Structural_Violence`.`EducationAccess` (
    `id` INT PRIMARY KEY,
    `year` YEAR(4),
    `basic_education_centers_per_100k` FLOAT,
    `middle_education_centers_per_100k` FLOAT,
    `technical_professional_centers_per_100k` FLOAT,
    `university_centers_per_100k` FLOAT,
    `subin_education` FLOAT,
    `Municipalitie_Information_Municipalities_id` INT,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`FloorType_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`FloorType_influence`;
CREATE TABLE IF NOT EXISTS `Structural_Violence`.`FloorType_influence` (
    `id` INT PRIMARY KEY,
    `Probes_references_id` INT,
    `Municipalitie_Information_Municipalities_id` INT,
    `count_cases_true` INT,
    `subin_VidegamesconsoleOwnership` FLOAT,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`),
    FOREIGN KEY (`Probes_references_id`)
        REFERENCES `RelationsAndConclusions`.`Probes_references` (`id`)
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`FloorType_subindicator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`FloorType_subindicator`;
CREATE TABLE IF NOT EXISTS `Structural_Violence`.`FloorType_subindicator` (
    `id` INT PRIMARY KEY,
    `FloorType_subindicator` FLOAT,
    `Municipalitie_Information_Municipalities_id` INT,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`HealthAccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`HealthAccess`;
CREATE TABLE IF NOT EXISTS `Structural_Violence`.`HealthAccess` (
    `id` INT PRIMARY KEY,
    `Municipalitie_Information_Municipalities_id` INT,
    `year` YEAR(4),
    `first_level_centers_per_100k` FLOAT,
    `second_level_centers_per_100k` FLOAT,
    `third_level_centers_per_100k` FLOAT,
    `subin_health` FLOAT,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`HealthCenters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`HealthCenters`;
CREATE TABLE IF NOT EXISTS `Structural_Violence`.`HealthCenters` (
    `id` INT PRIMARY KEY,
    `health_center_id` INT UNIQUE,
    `health_center_name` VARCHAR(255),
    `care_level` VARCHAR(255),
    `Municipalitie_Information_Municipalities_id` INT,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`Inequality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`Inequality`;
CREATE TABLE IF NOT EXISTS `Structural_Violence`.`Inequality` (
    `municipality_id` INT,
    `gini_index` FLOAT,
    `Municipalitie_Information_Municipalities_id` INT PRIMARY KEY,
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);
-- -----------------------------------------------------
-- Table `Structural_Violence`.`Poverty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`Poverty`;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`Poverty` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `municipality_id` INT NOT NULL,
    `mpi` FLOAT NULL DEFAULT NULL,
    `monetary_pi` FLOAT NULL DEFAULT NULL,
    `extreme_monetary_pi` FLOAT NULL DEFAULT NULL,
    `unsatisfied_basic_needs` FLOAT NULL DEFAULT NULL,
    `subin_poverty` FLOAT NULL DEFAULT NULL,
    FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`RoomPerBedroom_indicator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`RoomPerBedroom_indicator`;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`RoomPerBedroom_indicator` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `year` YEAR NULL DEFAULT NULL,
    `measurement` INT NULL DEFAULT NULL,
    `subin_room_per_bedroom` INT NULL DEFAULT NULL,
    `municipality_id` INT NOT NULL,
    FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`RoomsperBedroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`RoomsperBedroom`;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`RoomsperBedroom` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `stu_ref_id` INT NOT NULL,
    `rooms_per_bedroom` INT NULL DEFAULT NULL,
    FOREIGN KEY (`stu_ref_id`)
        REFERENCES `RelationsAndConclusions`.`STU_reference` (`id`)
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`STU_Floor_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`STU_Floor_type`;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`STU_Floor_type` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `year` YEAR NULL DEFAULT NULL,
    `subin_work_hours` INT NOT NULL,
    `stu_ref_id` INT NOT NULL,
    `floor_type` INT NULL DEFAULT NULL
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`StructuralViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`StructuralViolenceIndex`;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`StructuralViolenceIndex` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `year` YEAR NULL DEFAULT NULL,
    `subin_education_access` FLOAT NULL DEFAULT NULL,
    `subin_health_access` FLOAT NULL DEFAULT NULL,
    `subin_inequality` FLOAT NULL DEFAULT NULL,
    `subin_poverty` FLOAT NULL DEFAULT NULL,
    `subin_structural_influencers` FLOAT NULL DEFAULT NULL,
    `structural_violence_index` FLOAT NULL DEFAULT NULL,
    `municipality_id` INT NOT NULL,
    FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`Stu_CarOwnershipcases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`Stu_CarOwnershipcases`;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`Stu_CarOwnershipcases` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `car_ownership` TINYINT NULL DEFAULT NULL,
    `stu_ref_id` INT NOT NULL
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`Stu_VideoGamesOwnershipcases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`Stu_VideoGamesOwnershipcases`;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`Stu_VideoGamesOwnershipcases` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `videogames_ownership` TINYINT NULL DEFAULT NULL,
    `stu_ref_id` INT NOT NULL
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`Stu_WashingMachine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`Stu_WashingMachine`;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`Stu_WashingMachine` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `have_machine` TINYINT NULL,
    `stu_ref_id` INT NOT NULL
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`VidegamesconsoleOwnership_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`VidegamesconsoleOwnership_influence`;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`VidegamesconsoleOwnership_influence` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `probes_ref_id` INT NOT NULL,
    `municipality_id` INT NOT NULL,
    `count_cases_true` INT NULL DEFAULT NULL,
    `count_cases_false` INT NULL DEFAULT NULL,
    `subin_videogames_ownership` FLOAT NULL DEFAULT NULL,
     FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`WashingMachineOwnership_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`WashingMachineOwnership_influence`;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`WashingMachineOwnership_influence` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `count_cases_true` INT NULL DEFAULT NULL,
    `subin_washing_machine` FLOAT NULL DEFAULT NULL,
    `municipality_id` INT NOT NULL,
     FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`WorkStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`WorkStatus`;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`WorkStatus` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `year` YEAR NULL DEFAULT NULL,
    `subin_work_status` INT NULL DEFAULT NULL,
    `municipality_id` INT NOT NULL,
     FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Structural_Violence`.`stu_WorkHours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`stu_WorkHours`;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`stu_WorkHours` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `year` YEAR NULL DEFAULT NULL,
    `stu_ref_id` INT NOT NULL,
    `work_hours` INT NULL DEFAULT NULL,
	FOREIGN KEY (`stu_ref_id`)
	REFERENCES `RelationsAndConclusions`.`STU_reference` (`id`)
);

USE `Phisical_violence` ;
-- -----------------------------------------------------
-- Table `Phisical_violence`.`HomicideRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`HomicideRate`;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`HomicideRate` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `municipality_id` INT,
    `year` YEAR,
    `cases` INT,
    `rate_per_100k` INT,
    `subin_homicide` INT,
     FOREIGN KEY (`municipality_id`)
	 REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Phisical_violence`.`PhysicalViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`PhysicalViolenceIndex`;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`PhysicalViolenceIndex` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `municipality_id` INT,
    `year` YEAR,
    `subin_homicide` INT,
    `subin_suicide` INT,
    `subin_domestic` INT,
    `subin_violence_children_youth` INT,
    `subin_child_abuse` INT,
    `violence_index` INT,
     FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Phisical_violence`.`PhysicalViolenceInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`PhysicalViolenceInformation`;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`PhysicalViolenceInformation` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `violence_type` VARCHAR(255),
    `municipality_id` INT,
    `cases` INT,
    `year` YEAR,
     FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Phisical_violence`.`SuicideRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`SuicideRate`;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`SuicideRate` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `municipality_id` INT,
    `year` YEAR,
    `cases` INT,
    `rate_per_100k` FLOAT,
    `subin_suicide` INT,
     FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

-- -----------------------------------------------------
-- Table `Phisical_violence`.`ViolenceAgainstChildrenAndYouth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`ViolenceAgainstChildrenAndYouth`;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`ViolenceAgainstChildrenAndYouth` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `municipality_id` INT,
    `year` YEAR,
    `cases` INT,
    `rate_per_100k` INT,
    `subin_violence_children_youth` INT,
     FOREIGN KEY (`municipality_id`)
        REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`id`)
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
