-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 22:04:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RelationsAndConclusions
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `RelationsAndConclusions` ;

-- -----------------------------------------------------
-- Schema RelationsAndConclusions
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RelationsAndConclusions` ;
-- -----------------------------------------------------
-- Schema Cultural_violence
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Cultural_violence` ;

-- -----------------------------------------------------
-- Schema Cultural_violence
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cultural_violence` ;
-- -----------------------------------------------------
-- Schema GENDER_VIOLENCE
-- -----------------------------------------------------
-- 	
DROP SCHEMA IF EXISTS `GENDER_VIOLENCE` ;

-- -----------------------------------------------------
-- Schema GENDER_VIOLENCE
--
-- 	
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GENDER_VIOLENCE` ;
-- -----------------------------------------------------
-- Schema Structural_Violence
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Structural_Violence` ;

-- -----------------------------------------------------
-- Schema Structural_Violence
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Structural_Violence` ;
-- -----------------------------------------------------
-- Schema Phisical_violence
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Phisical_violence` ;

-- -----------------------------------------------------
-- Schema Phisical_violence
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Phisical_violence` ;
USE `RelationsAndConclusions` ;

-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`EducationalCenters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`EducationalCenters` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`EducationalCenters` (
  `id` INT NULL DEFAULT NULL,
  `educational_center_id` INT NULL DEFAULT NULL,
  `educational_center_name` VARCHAR(255) NULL DEFAULT NULL,
  `teaching_level` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  UNIQUE INDEX (`educational_center_id` ASC) VISIBLE,
  INDEX `fk_EducationalCenters_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_EducationalCenters_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`Municipalitie_Information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`Municipalitie_Information` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`Municipalitie_Information` (
  `Municipalities_id` INT NOT NULL,
  `Municipalitie_name` VARCHAR(45) NOT NULL,
  `Department_name` VARCHAR(45) NOT NULL,
  `ID_Deparment` INT NOT NULL,
  PRIMARY KEY (`Municipalities_id`),
  UNIQUE INDEX `Municipalities_id_UNIQUE` (`Municipalities_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`PopulationInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`PopulationInformation` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`PopulationInformation` (
  `id` INT NULL DEFAULT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `population` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `YEARS_idYEARS`, `Municipalitie_Information_Municipalities_id`),
  UNIQUE INDEX (`population` ASC) VISIBLE,
  INDEX `fk_PopulationInformation_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_PopulationInformation_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
DEFAULT CHARACTER SET = cp1250;


-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`Probes_references`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`Probes_references` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`Probes_references` (
  `id` INT NOT NULL,
  `Date` DATE NULL,
  `People_Who_takes_probes` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` USING BTREE (`id`) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RelationsAndConclusions`.`STU_reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RelationsAndConclusions`.`STU_reference` ;

CREATE TABLE IF NOT EXISTS `RelationsAndConclusions`.`STU_reference` (
  `id` INT NOT NULL,
  `ID_Student` VARCHAR(45) NULL,
  `EducationalCenters_id` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `Probes_references_idProbes_references` INT NOT NULL,
  PRIMARY KEY (`id`, `EducationalCenters_id`, `Municipalitie_Information_Municipalities_id`, `Probes_references_idProbes_references`),
  INDEX `fk_STU_reference_EducationalCenters1_idx` (`EducationalCenters_id` ASC) VISIBLE,
  INDEX `fk_STU_reference_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_STU_reference_Probes_references1_idx` (`Probes_references_idProbes_references` ASC) VISIBLE,
  UNIQUE INDEX `Id_stu_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_STU_reference_EducationalCenters1`
    FOREIGN KEY (`EducationalCenters_id`)
    REFERENCES `RelationsAndConclusions`.`EducationalCenters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STU_reference_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STU_reference_Probes_references1`
    FOREIGN KEY (`Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `Cultural_violence` ;

-- -----------------------------------------------------
-- Table `Cultural_violence`.`Books_for_Family_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Books_for_Family_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Books_for_Family_influence` (
  `id` INT NOT NULL,
  `year` YEAR(4) NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `books_for_family_indicator` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  UNIQUE INDEX `id_Stu_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Books_for_Family_influence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_Books_for_Family_influence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`CulturalInfluence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`CulturalInfluence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`CulturalInfluence` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `Year` YEAR(4) NULL,
  `ethnic_Influencer_indicator` DECIMAL NOT NULL,
  `books_for_family_indicator` DECIMAL NOT NULL,
  `Stu_internet_influence_indicator` DECIMAL NOT NULL,
  `Stu_read_for_pleasure_indicator` DECIMAL NOT NULL,
  PRIMARY KEY (`Id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_CulturalInfluence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_CulturalInfluence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`CulturalViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`CulturalViolenceIndex` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`CulturalViolenceIndex` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NOT NULL,
  `year` YEAR(4) NULL,
  `subin_Ancestry_homicide` FLOAT NULL DEFAULT NULL,
  `subin_Ancestry_suicide` FLOAT NULL DEFAULT NULL,
  `subin_vulnerable_groups_homicide` FLOAT NULL DEFAULT NULL,
  `subin_vulnerability_suicide` FLOAT NULL DEFAULT NULL,
  `contex_violence_index` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `Iindx_cultural_violence_index` (`contex_violence_index` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Father_Educational_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Father_Educational_information` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Father_Educational_information` (
  `id` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `Year` YEAR(4) NULL,
  `Father_Educational_influence` DECIMAL(2) NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  UNIQUE INDEX `id_Stu_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Father_Educational_influence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_Father_Educational_influence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Hours_of_Reading_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Hours_of_Reading_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Hours_of_Reading_influence` (
  `id` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `Year` YEAR(4) NULL,
  `Hours_of_reading_indicator` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  UNIQUE INDEX `id_Stu_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Hours_of_Reading_influence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_Hours_of_Reading_influence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`InternetAccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`InternetAccess` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`InternetAccess` (
  `id` INT NULL DEFAULT NULL,
  `municipaliti_ratio_Internet_acces` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Cultural_violence`.`InternetAccess_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`InternetAccess_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`InternetAccess_influence` (
  `id` INT NULL AUTO_INCREMENT,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `year` YEAR(4) NULL,
  `count_cases_true` INT NULL DEFAULT NULL,
  `subin_Internet_access` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_InternetAccess_influence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_InternetAccess_influence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Interpersonal_Conflicts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Interpersonal_Conflicts` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Interpersonal_Conflicts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Year` YEAR(4) NULL,
  `PopulationInformation_id` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `occurrences` INT NULL DEFAULT NULL,
  `subin_Interpersonal_conflicts` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `PopulationInformation_id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `Iindxsubin_vulnerable_groups_homicide` (`subin_Interpersonal_conflicts` ASC) VISIBLE,
  INDEX `fk_Interpersonal_Conflicts_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_Interpersonal_Conflicts_PopulationInformation1_idx` (`PopulationInformation_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Interpersonal_Conflicts_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interpersonal_Conflicts_PopulationInformation1`
    FOREIGN KEY (`PopulationInformation_id`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Interpersonal_Homicide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Interpersonal_Homicide` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Interpersonal_Homicide` (
  `id` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `PopulationInformation_id` INT NOT NULL,
  `YEARS` YEAR(4) NOT NULL,
  `occurrences` INT NULL DEFAULT NULL,
  `subin_vulnerable_groups_homicide` FLOAT GENERATED ALWAYS AS (),
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `PopulationInformation_id`),
  INDEX `Iindxsubin_vulnerable_groups_homicide` (`subin_vulnerable_groups_homicide` ASC) VISIBLE,
  INDEX `fk_Interpersonal_Homicide_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_Interpersonal_Homicide_PopulationInformation1_idx` (`PopulationInformation_id` ASC) VISIBLE,
  CONSTRAINT `fk_Interpersonal_Homicide_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interpersonal_Homicide_PopulationInformation1`
    FOREIGN KEY (`PopulationInformation_id`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Mother_Educational_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Mother_Educational_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Mother_Educational_influence` (
  `id` INT NOT NULL,
  `Mother_Educational_influence` DOUBLE NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  UNIQUE INDEX `id_Stu_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Mother_Educational_influence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_Mother_Educational_influence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`RACIAL_ANC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`RACIAL_ANC` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`RACIAL_ANC` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cultural_violence`.`RacialAncestryHomicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`RacialAncestryHomicideViolence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`RacialAncestryHomicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `PopulationInformation_id` INT NOT NULL,
  `RACIAL_ANC_idRACIAL_ANC` INT NOT NULL,
  `YEARS_idYEARS` INT NOT NULL,
  `occurrences` INT NULL DEFAULT NULL,
  `subin_homicide` FLOAT GENERATED ALWAYS AS (),
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `PopulationInformation_id`, `RACIAL_ANC_idRACIAL_ANC`, `YEARS_idYEARS`),
  INDEX `Iindx_subin_homicide` (`subin_homicide` ASC) VISIBLE,
  INDEX `fk_RacialAncestryHomicideViolence_Municipalitie_Information_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_RacialAncestryHomicideViolence_PopulationInformation1_idx` (`PopulationInformation_id` ASC) VISIBLE,
  INDEX `fk_RacialAncestryHomicideViolence_RACIAL_ANC1_idx` (`RACIAL_ANC_idRACIAL_ANC` ASC) VISIBLE,
  CONSTRAINT `fk_RacialAncestryHomicideViolence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RacialAncestryHomicideViolence_PopulationInformation1`
    FOREIGN KEY (`PopulationInformation_id`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RacialAncestryHomicideViolence_RACIAL_ANC1`
    FOREIGN KEY (`RACIAL_ANC_idRACIAL_ANC`)
    REFERENCES `Cultural_violence`.`RACIAL_ANC` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`RacialAncestrySuicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`RacialAncestrySuicideViolence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`RacialAncestrySuicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `RACIAL_ANC_idRACIAL_ANC` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `PopulationInformation_id` INT NOT NULL,
  `Year` YEAR(4) NULL,
  `occurrences` INT NULL DEFAULT NULL,
  `subin_suicide` FLOAT GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`id`, `RACIAL_ANC_idRACIAL_ANC`, `Municipalitie_Information_Municipalities_id`, `PopulationInformation_id`),
  INDEX `Iindx_subin_suicide` (`subin_suicide` ASC) VISIBLE,
  INDEX `fk_RacialAncestrySuicideViolence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_RacialAncestrySuicideViolence_PopulationInformation1_idx` (`PopulationInformation_id` ASC) VISIBLE,
  INDEX `fk_RacialAncestrySuicideViolence_RACIAL_ANC1_idx` (`RACIAL_ANC_idRACIAL_ANC` ASC) VISIBLE,
  CONSTRAINT `fk_RacialAncestrySuicideViolence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RacialAncestrySuicideViolence_PopulationInformation1`
    FOREIGN KEY (`PopulationInformation_id`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RacialAncestrySuicideViolence_RACIAL_ANC1`
    FOREIGN KEY (`RACIAL_ANC_idRACIAL_ANC`)
    REFERENCES `Cultural_violence`.`RACIAL_ANC` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`SociopoliticHomicide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`SociopoliticHomicide` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`SociopoliticHomicide` (
  `id` INT NULL DEFAULT NULL,
  `PopulationInformation_id` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `cases` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `PopulationInformation_id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_SociopoliticHomicide_PopulationInformation1_idx` (`PopulationInformation_id` ASC) VISIBLE,
  INDEX `fk_SociopoliticHomicide_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_SociopoliticHomicide_PopulationInformation1`
    FOREIGN KEY (`PopulationInformation_id`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SociopoliticHomicide_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Stu_Father_educational_Level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_Father_educational_Level` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_Father_educational_Level` (
  `Id` INT NOT NULL,
  `STU_reference_id` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  `EducationalCenters_id` INT NOT NULL,
  `EducationalCenters_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `Stu_Father_educational_Levelcol` INT NULL,
  PRIMARY KEY (`Id`, `STU_reference_id`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`, `EducationalCenters_id`, `EducationalCenters_Municipalitie_Information_Municipalities_id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Stu_Father_educational_Level_STU_reference1_idx` (`STU_reference_id` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  INDEX `fk_Stu_Father_educational_Level_EducationalCenters1_idx` (`EducationalCenters_id` ASC, `EducationalCenters_Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_Stu_Father_educational_Level_STU_reference1`
    FOREIGN KEY (`STU_reference_id` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`id` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_Father_educational_Level_EducationalCenters1`
    FOREIGN KEY (`EducationalCenters_id` , `EducationalCenters_Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`EducationalCenters` (`id` , `Municipalitie_Information_Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Stu_books_for_Family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_books_for_Family` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_books_for_Family` (
  `id` INT NOT NULL,
  `STU_reference_id` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  `Stu_books_for_Familycol` INT NULL,
  PRIMARY KEY (`id`, `STU_reference_id`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`),
  INDEX `fk_Stu_books_for_Family_STU_reference1_idx` (`STU_reference_id` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  CONSTRAINT `fk_Stu_books_for_Family_STU_reference1`
    FOREIGN KEY (`STU_reference_id` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`id` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Stu_hours_Internet_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_hours_Internet_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_hours_Internet_influence` (
  `id` INT NOT NULL,
  `Probes_references_id` INT NOT NULL,
  `Probes_references_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_id` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  `Hours_of_ dedication` INT NULL,
  PRIMARY KEY (`id`, `Probes_references_id`, `Probes_references_Municipalitie_Information_Municipalities_id`, `STU_reference_id`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`),
  INDEX `fk_Stu_hours_Internet_influence_Probes_references1_idx` (`Probes_references_id` ASC, `Probes_references_Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_Stu_hours_Internet_influence_STU_reference1_idx` (`STU_reference_id` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  CONSTRAINT `fk_Stu_hours_Internet_influence_Probes_references1`
    FOREIGN KEY (`Probes_references_id`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_hours_Internet_influence_STU_reference1`
    FOREIGN KEY (`STU_reference_id` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`id` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Stu_hours_reading_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_hours_reading_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_hours_reading_influence` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `STU_reference_Id_stu` INT NOT NULL,
  `Probes_references_id` INT NOT NULL,
  `Hours_of_ dedication` INT NOT NULL,
  `Year` YEAR(4) NOT NULL,
  PRIMARY KEY (`Id`, `STU_reference_Id_stu`, `Probes_references_id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Stu_hours_reading_influence_Probes_references1_idx` (`Probes_references_id` ASC) VISIBLE,
  INDEX `fk_Stu_hours_reading_influence_STU_reference1_idx` (`STU_reference_Id_stu` ASC) VISIBLE,
  CONSTRAINT `fk_Stu_hours_reading_influence_Probes_references1`
    FOREIGN KEY (`Probes_references_id`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stu_hours_reading_influence_STU_reference1`
    FOREIGN KEY (`STU_reference_Id_stu`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`Stu_mother_educational_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`Stu_mother_educational_level` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`Stu_mother_educational_level` (
  `id` INT NOT NULL,
  `STU_reference_id` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  `Stu_mother_educational_levelcol` INT NULL,
  PRIMARY KEY (`id`, `STU_reference_id`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Stu_mother_educational_level_STU_reference1_idx` (`STU_reference_id` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  CONSTRAINT `fk_Stu_mother_educational_level_STU_reference1`
    FOREIGN KEY (`STU_reference_id` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`id` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`VULNERABLE_GROUPS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`VULNERABLE_GROUPS` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`VULNERABLE_GROUPS` (
  `idVULNERABLE_GROUPS` INT NOT NULL,
  `VULNERABLE_GROUPScol` VARCHAR(45) NULL,
  PRIMARY KEY (`idVULNERABLE_GROUPS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cultural_violence`.`VulnerableGroupsHomicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`VulnerableGroupsHomicideViolence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`VulnerableGroupsHomicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `PopulationInformation_id` INT NOT NULL,
  `PopulationInformation_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `VULNERABLE_GROUPS_idVULNERABLE_GROUPS` INT NOT NULL,
  `Year` YEAR(4) NULL,
  `cases` INT NULL,
  `Indicator` DECIMAL(2) NULL,
  PRIMARY KEY (`id`, `PopulationInformation_id`, `PopulationInformation_Municipalitie_Information_Municipalities_id`, `VULNERABLE_GROUPS_idVULNERABLE_GROUPS`),
  INDEX `fk_VulnerableGroupsHomicideViolence_PopulationInformation1_idx` (`PopulationInformation_id` ASC, `PopulationInformation_Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_VulnerableGroupsHomicideViolence_VULNERABLE_GROUPS1_idx` (`VULNERABLE_GROUPS_idVULNERABLE_GROUPS` ASC) VISIBLE,
  CONSTRAINT `fk_VulnerableGroupsHomicideViolence_PopulationInformation1`
    FOREIGN KEY (`PopulationInformation_id` , `PopulationInformation_Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id` , `Municipalitie_Information_Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VulnerableGroupsHomicideViolence_VULNERABLE_GROUPS1`
    FOREIGN KEY (`VULNERABLE_GROUPS_idVULNERABLE_GROUPS`)
    REFERENCES `Cultural_violence`.`VULNERABLE_GROUPS` (`idVULNERABLE_GROUPS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`VulnerableGroupsSuicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`VulnerableGroupsSuicideViolence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`VulnerableGroupsSuicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `VULNERABLE_GROUPS_idVULNERABLE_GROUPS` INT NOT NULL,
  `PopulationInformation_id` INT NOT NULL,
  `PopulationInformation_YEARS_idYEARS` INT NOT NULL,
  `PopulationInformation_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `occurrences` INT NULL DEFAULT NULL,
  `subin_vulnerable_groups_suicide` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `VULNERABLE_GROUPS_idVULNERABLE_GROUPS`, `PopulationInformation_id`, `PopulationInformation_YEARS_idYEARS`, `PopulationInformation_Municipalitie_Information_Municipalities_id`),
  INDEX `Iindxsubin_vulnerable_groups_suicide` (`subin_vulnerable_groups_suicide` ASC) VISIBLE,
  INDEX `fk_VulnerableGroupsSuicideViolence_VULNERABLE_GROUPS1_idx` (`VULNERABLE_GROUPS_idVULNERABLE_GROUPS` ASC) VISIBLE,
  INDEX `fk_VulnerableGroupsSuicideViolence_PopulationInformation1_idx` (`PopulationInformation_id` ASC, `PopulationInformation_YEARS_idYEARS` ASC, `PopulationInformation_Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_VulnerableGroupsSuicideViolence_VULNERABLE_GROUPS1`
    FOREIGN KEY (`VULNERABLE_GROUPS_idVULNERABLE_GROUPS`)
    REFERENCES `Cultural_violence`.`VULNERABLE_GROUPS` (`idVULNERABLE_GROUPS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VulnerableGroupsSuicideViolence_PopulationInformation1`
    FOREIGN KEY (`PopulationInformation_id` , `PopulationInformation_YEARS_idYEARS` , `PopulationInformation_Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`PopulationInformation` (`id` , `YEARS_idYEARS` , `Municipalitie_Information_Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`gender(Victim)`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`gender(Victim)` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`gender(Victim)` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cultural_violence`.`stu_haveEthnia_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`stu_haveEthnia_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`stu_haveEthnia_influence` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `STU_reference_Id_stu` INT NOT NULL,
  `Probes_references_idProbes_references` INT NOT NULL,
  `year` YEAR(4) NOT NULL,
  `have_Ethia` TINYINT NULL,
  PRIMARY KEY (`id`, `STU_reference_Id_stu`, `Probes_references_idProbes_references`),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_stu_haveEthnia_influence_Probes_references1_idx` (`Probes_references_idProbes_references` ASC) VISIBLE,
  INDEX `fk_stu_haveEthnia_influence_STU_reference1_idx` (`STU_reference_Id_stu` ASC) VISIBLE,
  CONSTRAINT `fk_stu_haveEthnia_influence_Probes_references1`
    FOREIGN KEY (`Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_haveEthnia_influence_STU_reference1`
    FOREIGN KEY (`STU_reference_Id_stu`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Cultural_violence`.`stu_haveInternet_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cultural_violence`.`stu_haveInternet_influence` ;

CREATE TABLE IF NOT EXISTS `Cultural_violence`.`stu_haveInternet_influence` (
  `ID` INT NOT NULL,
  `have_Internet` TINYINT NULL,
  `STU_reference_id` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  PRIMARY KEY (`ID`, `STU_reference_id`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`),
  INDEX `fk_stu_haveInternet_influence_STU_reference1_idx` (`STU_reference_id` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  CONSTRAINT `fk_stu_haveInternet_influence_STU_reference1`
    FOREIGN KEY (`STU_reference_id` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`id` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `GENDER_VIOLENCE` ;

-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`DomesticViolenceNonGenderBAsedRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`DomesticViolenceNonGenderBAsedRate` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`DomesticViolenceNonGenderBAsedRate` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `domestic_violence_rate_per_100k` INT NULL DEFAULT NULL,
  `subin_domestic_violence` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_DomesticViolenceNonGenderBAsedRate_Municipalitie_Informa_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_DomesticViolenceNonGenderBAsedRate_Municipalitie_Informati1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`DomesticViolenceRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`DomesticViolenceRate` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`DomesticViolenceRate` (
  `id` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `gender(Victim)_id` INT NOT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `domestic_violence_rate_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_domestic_violence` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `gender(Victim)_id`),
  INDEX `fk_DomesticViolenceRate_gender(Victim)1_idx` (`gender(Victim)_id` ASC) VISIBLE,
  INDEX `fk_DomesticViolenceRate_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_DomesticViolenceRate_gender(Victim)1`
    FOREIGN KEY (`gender(Victim)_id`)
    REFERENCES `Cultural_violence`.`gender(Victim)` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DomesticViolenceRate_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`GenderHomicideRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderHomicideRate` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderHomicideRate` (
  `id` INT NULL DEFAULT NULL,
  `gender_id` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `homicide_rate_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_gender_homicide` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `gender_id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_GenderHomicideRate_gender_idx` (`gender_id` ASC) VISIBLE,
  INDEX `fk_GenderHomicideRate_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_GenderHomicideRate_gender`
    FOREIGN KEY (`gender_id`)
    REFERENCES `Cultural_violence`.`gender(Victim)` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GenderHomicideRate_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`GenderInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderInformation` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderInformation` (
  `id` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `gender_name` VARCHAR(255) NULL DEFAULT NULL,
  `population_by_gender` FLOAT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_GenderInformation_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_GenderInformation_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`GenderViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderViolenceIndex` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderViolenceIndex` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `subin_partner_homicide` FLOAT NULL DEFAULT NULL,
  `subin_romantic_suicide` FLOAT NULL DEFAULT NULL,
  `subin_vulnerability_homicide` FLOAT NULL DEFAULT NULL,
  `subin_vulnerability_suicide` FLOAT NULL DEFAULT NULL,
  `subin_gender_homicide` FLOAT NULL DEFAULT NULL,
  `subin_domestic_violence` FLOAT NULL DEFAULT NULL,
  `gender_violence_index` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`GenderVulnerabilityHomicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderVulnerabilityHomicideViolence` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderVulnerabilityHomicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `vulnerability_factor_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `homicide_rate_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_vulnerability_homicide` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`GenderVulnerabilitySuicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`GenderVulnerabilitySuicideViolence` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`GenderVulnerabilitySuicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `vulnerability_factor_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `suicide_rate_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_vulnerability_suicide` FLOAT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `gender(Victim)_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `gender(Victim)_id`),
  INDEX `fk_GenderVulnerabilitySuicideViolence_Municipalitie_Informa_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_GenderVulnerabilitySuicideViolence_gender(Victim)1_idx` (`gender(Victim)_id` ASC) VISIBLE,
  CONSTRAINT `fk_GenderVulnerabilitySuicideViolence_Municipalitie_Informati1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GenderVulnerabilitySuicideViolence_gender(Victim)1`
    FOREIGN KEY (`gender(Victim)_id`)
    REFERENCES `Cultural_violence`.`gender(Victim)` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`IcfesResultsAnalysis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`IcfesResultsAnalysis` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`IcfesResultsAnalysis` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `gender_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `average_math_score` FLOAT NULL DEFAULT NULL,
  `average_natural_sciences_score` FLOAT NULL DEFAULT NULL,
  `average_social_and_citizenship_score` FLOAT NULL DEFAULT NULL,
  `average_languages_score` FLOAT NULL DEFAULT NULL,
  `average_foreign_language_score` FLOAT NULL DEFAULT NULL,
  `average_global_score` FLOAT NULL DEFAULT NULL,
  `subin_global_score` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`PartnerHomicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`PartnerHomicideViolence` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`PartnerHomicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `homicide_rate_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_partner_homicide` FLOAT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `gender(Victim)_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `gender(Victim)_id`),
  INDEX `fk_PartnerHomicideViolence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_PartnerHomicideViolence_gender(Victim)1_idx` (`gender(Victim)_id` ASC) VISIBLE,
  CONSTRAINT `fk_PartnerHomicideViolence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PartnerHomicideViolence_gender(Victim)1`
    FOREIGN KEY (`gender(Victim)_id`)
    REFERENCES `Cultural_violence`.`gender(Victim)` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `GENDER_VIOLENCE`.`RomanticSuicideViolence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GENDER_VIOLENCE`.`RomanticSuicideViolence` ;

CREATE TABLE IF NOT EXISTS `GENDER_VIOLENCE`.`RomanticSuicideViolence` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `gender_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `suicide_rate_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_romantic_suicide` FLOAT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `gender(Victim)_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`, `gender(Victim)_id`),
  INDEX `fk_RomanticSuicideViolence_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_RomanticSuicideViolence_gender(Victim)1_idx` (`gender(Victim)_id` ASC) VISIBLE,
  CONSTRAINT `fk_RomanticSuicideViolence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RomanticSuicideViolence_gender(Victim)1`
    FOREIGN KEY (`gender(Victim)_id`)
    REFERENCES `Cultural_violence`.`gender(Victim)` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `Structural_Violence` ;

-- -----------------------------------------------------
-- Table `Structural_Violence`.`CarOwnership_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`CarOwnership_influence` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`CarOwnership_influence` (
  `id` INT NULL DEFAULT NULL,
  `Probes_references_id` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `count_cases_true` INT NULL DEFAULT NULL,
  `count_cases_false` INT NULL DEFAULT NULL,
  `CarOwnership` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `Probes_references_id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_VidegamesconsoleOwnership_influence_Municipalitie_Inform_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_VidegamesconsoleOwnership_influence_Probes_references1_idx` (`Probes_references_id` ASC) VISIBLE,
  CONSTRAINT `fk_VidegamesconsoleOwnership_influence_Municipalitie_Informat10`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VidegamesconsoleOwnership_influence_Probes_references10`
    FOREIGN KEY (`Probes_references_id`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`EducationAccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`EducationAccess` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`EducationAccess` (
  `id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `basic_education_centers_per_100k` FLOAT NULL DEFAULT NULL,
  `middle_education_centers_per_100k` FLOAT NULL DEFAULT NULL,
  `technical_professional_centers_per_100k` FLOAT NULL DEFAULT NULL,
  `university_centers_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_education` FLOAT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_EducationAccess_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_EducationAccess_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`FloorType_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`FloorType_influence` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`FloorType_influence` (
  `id` INT NULL DEFAULT NULL,
  `Probes_references_id` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `count_cases_true` INT NULL DEFAULT NULL,
  `subin_VidegamesconsoleOwnership` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `Probes_references_id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_VidegamesconsoleOwnership_influence_Municipalitie_Inform_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_VidegamesconsoleOwnership_influence_Probes_references1_idx` (`Probes_references_id` ASC) VISIBLE,
  CONSTRAINT `fk_VidegamesconsoleOwnership_influence_Municipalitie_Informat11`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VidegamesconsoleOwnership_influence_Probes_references11`
    FOREIGN KEY (`Probes_references_id`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`FloorType_subindicator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`FloorType_subindicator` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`FloorType_subindicator` (
  `id` INT NULL DEFAULT NULL,
  `FloorType_subindicator` FLOAT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_FloorType_subindicator_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_FloorType_subindicator_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`HealthAccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`HealthAccess` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`HealthAccess` (
  `id` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `first_level_centers_per_100k` FLOAT NULL DEFAULT NULL,
  `second_level_centers_per_100k` FLOAT NULL DEFAULT NULL,
  `third_level_centers_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_health` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_HealthAccess_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_HealthAccess_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`HealthCenters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`HealthCenters` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`HealthCenters` (
  `id` INT NULL DEFAULT NULL,
  `health_center_id` INT NULL DEFAULT NULL,
  `health_center_name` VARCHAR(255) NULL DEFAULT NULL,
  `care_level` VARCHAR(255) NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  UNIQUE INDEX (`health_center_id` ASC) VISIBLE,
  INDEX `fk_HealthCenters_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_HealthCenters_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`Inequality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`Inequality` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`Inequality` (
  `municipality_id` INT NULL DEFAULT NULL,
  `gini_index` FLOAT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`Municipalitie_Information_Municipalities_id`),
  CONSTRAINT `fk_Inequality_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`Poverty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`Poverty` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`Poverty` (
  `id` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `multidimensional_poverty_index` FLOAT NULL DEFAULT NULL,
  `monetary_poverty_index` FLOAT NULL DEFAULT NULL,
  `extreme_monetary_poverty_index` FLOAT NULL DEFAULT NULL,
  `unsatisfied_basic_needs_index` FLOAT NULL DEFAULT NULL,
  `subin_poverty` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_Poverty_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_Poverty_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`RoomPerBedroom_indicator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`RoomPerBedroom_indicator` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`RoomPerBedroom_indicator` (
  `id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `measurement` INT NULL DEFAULT NULL,
  `subin_room_per_bedroom` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_RoomPerBedroom_indicator_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_RoomPerBedroom_indicator_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`RoomsperBedroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`RoomsperBedroom` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`RoomsperBedroom` (
  `id` INT NULL DEFAULT NULL,
  `VideoGames_Ownershipcases` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  `rooms_per_bedroom` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `VideoGames_Ownershipcases`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`),
  INDEX `fk_CarOwnershipcases_STU_reference1_idx` (`VideoGames_Ownershipcases` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  CONSTRAINT `fk_CarOwnershipcases_STU_reference100`
    FOREIGN KEY (`VideoGames_Ownershipcases` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`id` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`STU_Floor_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`STU_Floor_type` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`STU_Floor_type` (
  `id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `subin_work_hours` INT NOT NULL,
  `STU_reference_id` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  `FloorType` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `subin_work_hours`, `STU_reference_id`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`),
  INDEX `fk_WorkHours_Municipalitie_Information1_idx` (`subin_work_hours` ASC) VISIBLE,
  INDEX `fk_WorkHours_STU_reference1_idx` (`STU_reference_id` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  CONSTRAINT `fk_WorkHours_Municipalitie_Information10`
    FOREIGN KEY (`subin_work_hours`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WorkHours_STU_reference10`
    FOREIGN KEY (`STU_reference_id` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`id` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`StructuralViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`StructuralViolenceIndex` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`StructuralViolenceIndex` (
  `id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `subin_education_access` FLOAT NULL DEFAULT NULL,
  `subin_health_access` FLOAT NULL DEFAULT NULL,
  `subin_inequality` FLOAT NULL DEFAULT NULL,
  `subin_poverty` FLOAT NULL DEFAULT NULL,
  `subin_structural_influencers` FLOAT NULL DEFAULT NULL,
  `structural_violence_index` FLOAT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_StructuralViolenceIndex_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_StructuralViolenceIndex_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`Stu_CarOwnershipcases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`Stu_CarOwnershipcases` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`Stu_CarOwnershipcases` (
  `id` INT NULL DEFAULT NULL,
  `carOwnershipcases` TINYINT NULL DEFAULT NULL,
  `STU_reference_id` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  PRIMARY KEY (`id`, `STU_reference_id`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`),
  INDEX `fk_CarOwnershipcases_STU_reference1_idx` (`STU_reference_id` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  CONSTRAINT `fk_CarOwnershipcases_STU_reference1`
    FOREIGN KEY (`STU_reference_id` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`id` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`Stu_VideoGamesOwnershipcases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`Stu_VideoGamesOwnershipcases` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`Stu_VideoGamesOwnershipcases` (
  `id` INT NULL DEFAULT NULL,
  `VideoGames_Ownershipcases` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  `VideoGames_Ownershipcases` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `VideoGames_Ownershipcases`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`),
  INDEX `fk_CarOwnershipcases_STU_reference1_idx` (`VideoGames_Ownershipcases` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  CONSTRAINT `fk_CarOwnershipcases_STU_reference10`
    FOREIGN KEY (`VideoGames_Ownershipcases` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`id` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`Stu_WashingMachine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`Stu_WashingMachine` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`Stu_WashingMachine` (
  `id` INT NOT NULL,
  `STU_reference_Id_stu` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  `have_machine` TINYINT NULL,
  PRIMARY KEY (`id`, `STU_reference_Id_stu`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`),
  INDEX `fk_Stu_WashingMachine_STU_reference_idx` (`STU_reference_Id_stu` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  CONSTRAINT `fk_Stu_WashingMachine_STU_reference`
    FOREIGN KEY (`STU_reference_Id_stu` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`id` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Structural_Violence`.`VidegamesconsoleOwnership_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`VidegamesconsoleOwnership_influence` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`VidegamesconsoleOwnership_influence` (
  `id` INT NULL DEFAULT NULL,
  `Probes_references_id` INT NOT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `count_cases_true` INT NULL DEFAULT NULL,
  `count_cases_false` INT NULL DEFAULT NULL,
  `subin_VidegamesconsoleOwnership` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `Probes_references_id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_VidegamesconsoleOwnership_influence_Municipalitie_Inform_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  INDEX `fk_VidegamesconsoleOwnership_influence_Probes_references1_idx` (`Probes_references_id` ASC) VISIBLE,
  CONSTRAINT `fk_VidegamesconsoleOwnership_influence_Municipalitie_Informat1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VidegamesconsoleOwnership_influence_Probes_references1`
    FOREIGN KEY (`Probes_references_id`)
    REFERENCES `RelationsAndConclusions`.`Probes_references` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`WashingMachineOwnership_influence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`WashingMachineOwnership_influence` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`WashingMachineOwnership_influence` (
  `id` INT NULL DEFAULT NULL,
  `count_cases_true` INT NULL DEFAULT NULL,
  `subin_washing_machine` FLOAT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_WashingMachineOwnership_influence_Municipalitie_Informat_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_WashingMachineOwnership_influence_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`WorkStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`WorkStatus` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`WorkStatus` (
  `id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `subin_work_status` INT NULL DEFAULT NULL,
  `Municipalitie_Information_Municipalities_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Municipalitie_Information_Municipalities_id`),
  INDEX `fk_WorkStatus_Municipalitie_Information1_idx` (`Municipalitie_Information_Municipalities_id` ASC) VISIBLE,
  CONSTRAINT `fk_WorkStatus_Municipalitie_Information1`
    FOREIGN KEY (`Municipalitie_Information_Municipalities_id`)
    REFERENCES `RelationsAndConclusions`.`Municipalitie_Information` (`Municipalities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Structural_Violence`.`stu_WorkHours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Structural_Violence`.`stu_WorkHours` ;

CREATE TABLE IF NOT EXISTS `Structural_Violence`.`stu_WorkHours` (
  `id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `STU_reference_id` INT NOT NULL,
  `STU_reference_EducationalCenters_id` INT NOT NULL,
  `STU_reference_Municipalitie_Information_Municipalities_id` INT NOT NULL,
  `STU_reference_Probes_references_idProbes_references` INT NOT NULL,
  `work_hours` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `STU_reference_id`, `STU_reference_EducationalCenters_id`, `STU_reference_Municipalitie_Information_Municipalities_id`, `STU_reference_Probes_references_idProbes_references`),
  INDEX `fk_stu_WorkHours_STU_reference1_idx` (`STU_reference_id` ASC, `STU_reference_EducationalCenters_id` ASC, `STU_reference_Municipalitie_Information_Municipalities_id` ASC, `STU_reference_Probes_references_idProbes_references` ASC) VISIBLE,
  CONSTRAINT `fk_stu_WorkHours_STU_reference1`
    FOREIGN KEY (`STU_reference_id` , `STU_reference_EducationalCenters_id` , `STU_reference_Municipalitie_Information_Municipalities_id` , `STU_reference_Probes_references_idProbes_references`)
    REFERENCES `RelationsAndConclusions`.`STU_reference` (`id` , `EducationalCenters_id` , `Municipalitie_Information_Municipalities_id` , `Probes_references_idProbes_references`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `Phisical_violence` ;

-- -----------------------------------------------------
-- Table `Phisical_violence`.`FinalViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`FinalViolenceIndex` ;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`FinalViolenceIndex` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `subin_structural_violence` INT NULL DEFAULT NULL,
  `subin_cultural_violence` INT NULL DEFAULT NULL,
  `subin_gender_violence` INT NULL DEFAULT NULL,
  `subin_physical_violence` INT NULL DEFAULT NULL,
  `final_violence_index` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Phisical_violence`.`HomicideRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`HomicideRate` ;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`HomicideRate` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `homicide_rate_per_100k` INT NULL DEFAULT NULL,
  `subin_homicide` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Phisical_violence`.`PhysicalViolenceIndex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`PhysicalViolenceIndex` ;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`PhysicalViolenceIndex` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `subin_homicide` INT NULL DEFAULT NULL,
  `subin_suicide` INT NULL DEFAULT NULL,
  `subin_domestic_violence` INT NULL DEFAULT NULL,
  `subin_violence_against_children_and_youth` INT NULL DEFAULT NULL,
  `subin_child_abuse` INT NULL DEFAULT NULL,
  `physical_violence_index` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Phisical_violence`.`PhysicalViolenceInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`PhysicalViolenceInformation` ;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`PhysicalViolenceInformation` (
  `id` INT NULL DEFAULT NULL,
  `physical_violence_type` VARCHAR(255) NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Phisical_violence`.`SuicideRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`SuicideRate` ;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`SuicideRate` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `suicide_rate_per_100k` FLOAT NULL DEFAULT NULL,
  `subin_suicide` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Phisical_violence`.`ViolenceAgainstChildrenAndYouth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phisical_violence`.`ViolenceAgainstChildrenAndYouth` ;

CREATE TABLE IF NOT EXISTS `Phisical_violence`.`ViolenceAgainstChildrenAndYouth` (
  `id` INT NULL DEFAULT NULL,
  `Municipalities_id` INT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `cases` INT NULL DEFAULT NULL,
  `violence_against_children_and_youth_rate_per_100k` INT NULL DEFAULT NULL,
  `subin_violence_against_children_and_youth` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

USE `Cultural_violence` ;

-- -----------------------------------------------------
-- procedure Count_ethnic_influencer
-- -----------------------------------------------------

USE `Cultural_violence`;
DROP procedure IF EXISTS `Cultural_violence`.`Count_ethnic_influencer`;

DELIMITER $$
USE `Cultural_violence`$$
CREATE PROCEDURE `Count_ethnic_influencer` ()
BEGIN
CREATE EVENT update_ethnic_influencer
ON SCHEDULE EVERY 1 DAY
STARTS CURRENT_DATE
DO
    UPDATE 
        Cultural_violence.ethnic_Influencer
    SET 
        count_have_ethnia = (
            SELECT 
                COUNT(Cultural_violence.stu_haveEthnia_influence.haveethnia)
            FROM 
                Cultural_violence.stu_haveEthnia_influence
            INNER JOIN 
                RelationsAndConclusions.STU_reference 
            ON 
                Cultural_violence.stu_haveEthnia_influence.STU_reference_Id_stu = RelationsAndConclusions.STU_reference.Id_stu
            INNER JOIN 
                RelationsAndConclusions.Probes_references 
            ON 
                RelationsAndConclusions.STU_reference.Probes_references_IdProbes_references = RelationsAndConclusions.Probes_references.idProbes_references
            WHERE 
                RelationsAndConclusions.Probes_references.Year = Cultural_violence.ethnic_Influencer.Year
                AND RelationsAndConclusions.STU_reference.Municipalitie_information_Municipalities_id = Cultural_violence.ethnic_Influencer.Municipalitie_Information_Municipalities_id
                AND Cultural_violence.stu_haveEthnia_influence.haveethnia = TRUE
        );


END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
